### ISSUE TITLE
Error: "Couldn't determine the size of..."

### ISSUE THREAD

**Issue by whalecoiner** [snarfed/bridgy#1001]
Source: https://whalecoiner.com/notes/20201231t1913
Brid.gy log: https://brid.gy/log?start_time=1609507792&key=agdicmlkLWd5clILEg1QdWJsaXNoZWRQYWdlIitodHRwczovL3doYWxlY29pbmVyLmNvbS9ub3Rlcy8yMDIwMTIzMXQxOTEzDAsSB1B1Ymxpc2gYgICIwNDSmgoM

```
I 2021-01-01 14:16:34.401410 no refresh_token
I 2021-01-01 14:16:34.406790 urlopen GET https://whalecoiner.com/notes/20201231t1913/images-0-file-1609506824604-304032219.png/900 {}
I 2021-01-01 14:16:34.801619 Couldn't determine the size of <a href="https://whalecoiner.com/notes/20201231t1913/images-0-file-1609506824604-304032219.png/900">whalecoiner.com/notes/20201231...</a>;
```

Brid.gy is erroring when I try to publish this URL. It looks like it's tripping up over the image? 

Does anyone have any ideas why? (I tried it without the trailing `/900` URL image width modifier and I still got the same result).

**Comment by snarfed** [comment]
Nice sleuthing! And sorry for the trouble. Looks like your web server isn't serving the `Content-Length` HTTP header, which Bridgy checks for publishing images to Twitter because [Twitter has a 5MB limit](https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices#image-specs). Try adding that header?

**Comment by whalecoiner** [comment]
Ah, amazing! Dynamic image were the one asset I wasn't serving `Content-length` on! 😂 

Works fine now. Thanks for the help!
