### ISSUE TITLE
Reddit URL posts do not send webmentions.

### ISSUE THREAD

**Issue by kevincox** [snarfed/bridgy#1004]
Sorry if I am misunderstanding. I have read the FAQ and past issues mentioning this error but they don't seem to explain the issue.

It appears as though bridgy is now finding links to my website on Reddit but isn't sending any webmentions.

Log: https://brid.gy/log?start_time=1610368793&key=agdicmlkLWd5chcLEgZSZWRkaXQiC2tldmluY294X2NhDA

From an outside it looks like the following:

- The links are found successfully.
- It finds https://kevincox.ca in my profile.
- The POSSE discovery fails because I don't have a feed on my homepage (fine by me).
- Doesn't attempt to send any webmentions?

![image](https://user-images.githubusercontent.com/494012/104188652-8e025380-53e7-11eb-9cd0-4856325136ce.png)

(The error links to https://brid.gy/about#profile-links but I have a link in my profile)

I have also tried checking the logs for individual links but they appear to be basically empty https://brid.gy/log?start_time=1610370790&key=agdicmlkLWd5chQLEghSZXNwb25zZSIGamw3dXE5DA

My website doesn't support brotli compression.

Is this because the POSSE is failing? I don't think that should be relevant as the original link is in the Reddit post and I would like to receive all mentions of it.

**Comment by snarfed** [comment]
Thanks for the detailed sleuthing! Makes debugging a lot easier.

Looks like this is because we have a bit more to do before Bridgy handles Reddit submitted URLs themselves. Apologies, I don't really use Reddit myself or understand it very deeply, otherwise I would have caught this earlier. 😆

Specifically, granary converts Reddit posts to AS JSON like this:

```json
{
  "verb": "post",
  "id": "jnsv4i",
  "url": "https://reddit.com/r/NixOS/comments/jnsv4i/switching_to_nixos_on_desktop/",
  "object": {
    "objectType": "bookmark",
    "targetUrl": "https://kevincox.ca/2020/09/06/switching-to-desktop-nixos/",
    "..."
  }
  "..."
}
```

...so we need to grab `targetUrl` and add it to the list of candidate original post links. That should probably happen in [`Source.original_post_discovery`](https://github.com/snarfed/granary/blob/master/granary/source.py#L612-L687), in granary. Should hopefully be straightforward, @kevincox any interest in tackling that?

cc @stedn @jamietanna just in case you're curious!

**Comment by kevincox** [comment]
If no one else picks it up I might be able to find time. But I'm a little busy ATM. I'll post here if I have started working on it.

**Comment by snarfed** [comment]
Done! Reddit is still a bit rough on Bridgy in a few ways, but this at least should be fixed now. Thanks again for filing.
