### ISSUE TITLE
allow webmention endpoint discovery on non-2xx responses

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy#1012]
[This Mastodon toot](https://blimps.xyz/@Austin_Dern/105665532449151229) was posted in response to a toot (posted from my actual Mastodon account, as opposed to via Bridgy Fed) that links to a private entry. Even though the entry is private, it provides a `link` header that declares the endpoint, so this should be discoverable by brid.gy:

```
bucket:Publ main$ curl -i https://beesbuzz.biz/8461 | more
HTTP/2 401 
server: nginx/1.18.0 (Ubuntu)
date: Sat, 20 Feb 2021 10:25:43 GMT
content-type: text/html; charset=utf-8
content-length: 16019
link: <https://webmention.io/beesbuzz.biz/webmention>; rel="webmention"

<!DOCTYPE html>
<html><head>
<title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/_login?asset=css">
```

However, webmention.io did not receive any reply from brid.gy:

```
bucket:Publ main$ curl https://webmention.io/api/mentions.jf2?target=https://beesbuzz.biz/8461
{"type":"feed","name":"Webmentions","children":[]}
```

which tells me that brid.gy is only looking at `<link rel="webmention">` in the HTML rather than the `link` HTTP response headers per the [webmention endpoint discovery](https://www.w3.org/TR/webmention/#sender-discovers-receiver-webmention-endpoint) process.

**Comment by snarfed** [comment]
thanks for filing! the issue here isn't header discovery - bridgy has supported that forever - but instead the 401 response. bridgy currently only discovers webmention endpoints on 2xx responses. [we discussed this a bit in chat just now](https://chat.indieweb.org/dev/2021-02-20#t1613831930254700), and didn't come up with a strong rationale, but tentatively concluded that yes, discovery should still be possible on non-2xx responses. no ETA yet, but i can do that in bridgy.

**Comment by fluffy-critter** [comment]
Makes sense. But mentions to 401s will be very important for supporting private posts in general. Could there be an exception for that? For that matter I feel like any error page which declares an endpoint should still be consisted a valid target.

**Comment by snarfed** [comment]
cc @Ryuno-Ki since this lives inside webmention-tools, probably https://github.com/Ryuno-Ki/webmention-tools/blob/54409786327c2b43516c2b5b96e5d0a18a96c0f3/webmentiontools/discover.py#L64 and https://github.com/Ryuno-Ki/webmention-tools/blob/54409786327c2b43516c2b5b96e5d0a18a96c0f3/webmentiontools/discover.py#L79 .

**Comment by Ryuno-Ki** [comment]
No need to CC. I'm watching every issue here anyway :-D

I'm a bit on the fence regarding accepting 401s. I mean, It's Unauthorized for a reason.
But then again I have a hack in https://github.com/Ryuno-Ki/webmention-tools/blob/54409786327c2b43516c2b5b96e5d0a18a96c0f3/webmentiontools/send.py#L16-L18

So I'd rather see an issue on https://github.com/w3c/webmention/issues (**there** you should CC me - or drop the link in here so I can subscribe). Otherwise, you're about to develop an insular solution here (and drag me with you :-D ).

**Comment by snarfed** [comment]
Understood! @aaronpk, do we need explicit language in the spec to clarify this? Or should we interpret the current spec language as, discovery should continue even on HTTP error responses?

**Comment by Ryuno-Ki** [comment]
At least https://www.w3.org/TR/webmention/#sender-notifies-receiver says:

> Any 2xx response code MUST be considered a success.

It is undefined behaviour (right now) what shall happen on 401. (Like I spotted some other places).

**Comment by fluffy-critter** [comment]
Just because a resource is unauthorized to the third-party webmention sender doesn’t mean it’s unauthorized to the person sending the webmention. I mean, that’s the very issue that came up for me — the person sending the Mastodon-based reply to my private blog post can see the blog post (obviously) but brid.gy can’t, nor should it be able to. But it can still see that I’m *receiving* webmentions on that URL, even if it’s not authorized to get it.

I would think that providing a webmention endpoint is what declares the intent for what should happen with mentions, regardless of the HTTP status of the discovery request.

> At least https://www.w3.org/TR/webmention/#sender-notifies-receiver says:
> 
> > Any 2xx response code MUST be considered a success.
> 
> It is undefined behaviour (right now) what shall happen on 401. (Like I spotted some other places).

I believe that part of the spec is about sending the webmention itself, not about endpoint discovery. It’s the endpoint discovery that’s at question here.

**Comment by aaronpk** [comment]
> At least https://www.w3.org/TR/webmention/#sender-notifies-receiver says:

This section is talking about the response the sender gets from the webmention endpoint itself, the issue at hand is talking about discovering the webmention endpoint in the first place.

**Comment by snarfed** [comment]
> At least https://www.w3.org/TR/webmention/#sender-notifies-receiver says:
> 
> > Any 2xx response code MUST be considered a success.
> 
> It is undefined behaviour (right now) what shall happen on 401. (Like I spotted some other places).

Hey @aaronpk, can you confirm that expected behavior when discovery gets a non-2xx HTTP response is currently undefined? Totally ok, just checking.

**Comment by aaronpk** [comment]
There's nothing in the discovery section https://www.w3.org/TR/webmention/#sender-discovers-receiver-webmention-endpoint that talks about the difference in HTTP status codes when doing discovery. I suppose that means it's undefined, but you could also interpret that to mean you should ignore the HTTP status code when doing discovery...

**Comment by snarfed** [comment]
Ah, true! Nm, you're right, that "non-2xx" quote was from the sending section, not discovery. OK then we'll tentatively interpret it as applying to all HTTP status codes, ie discovery is still (mildly) expected to continue even on 4xx (like here) or 5xxes.

**Comment by snarfed** [comment]
Done!
