### ISSUE TITLE
Failed to fetch (mastodon syndication)

### ISSUE THREAD

**Issue by hoschi-it** [snarfed/bridgy#1020]
I followed the guide on publishing as good as I could, but nevertheless when I

- open [this mastodon user page](https://brid.gy/mastodon/@hoschi@mastodontech.de)
- "resend for post": https://hoschi-it.de/2021/03/14/plain-note-post-type/
- "discover"

I get the error: Failed to fetch hoschi-it.de/2021/03/14/pla... or find a Mastodon syndication link.

I double checked my formatting. The link `https://brid.gy/publish/mastodon` is there.
Is there anything wrong with my approach? Sorry, can't figure it out.

(P.S.: This subpage has never been syndicated before.)

**Comment by snarfed** [comment]
Hey, sorry for the confusion! That's actually the listen (backfeed) UI for sending back responses. We don't currently  support publishing to Mastodon interactive, via the UI, as mentioned in the yellow warning box on your user page, [due to this bug on their end.](https://github.com/tootsuite/mastodon/issues/12915) [Try publishing via webmention instead.](https://brid.gy/about#webmentions)

**Comment by hoschi-it** [comment]
Thanks @snarfed.
Maybe, it would be good to hide this form then?
