### ISSUE TITLE
Instagram syndication link found but not sending webmentions

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy#1098]
https://gregorlove.com/2021/12/cookies-were-made/ has a `u-syndication` of https://www.instagram.com/p/CXuwY4JLAGd/

The [crawl](https://brid.gy/log?start_time=1640200508&key=agdicmlkLWd5chkLEglJbnN0YWdyYW0iCmdyZWdvcmxvdmUM) of my site seems to have found those, but the last line looks like it's still seeing my [previous photo](https://gregorlove.com/2021/10/how-to-make-a-zombie-cash/) as the last public post, based on this part of the JSON:

`'last_public_post': datetime.datetime(2021, 11, 1, 7, 6, 33)`

Bridgy Chrome 0.3.5 options is showing:
```
Status: OK

Bridgy user page: brid.gy/instagram/gregorlove.com
Instagram account: gregorlove
Last success: 12/22/2021, 9:12:27 PM
Last attempt: 12/22/2021, 9:12:19 PM
Posts seen: 18
Comments seen: 116
Likes seen: 671
```

**Comment by snarfed** [comment]
Thanks for filing!

I suspect IG changed their HTML somehow. Your `/instagram/browser/profile` and `/instagram/browser/feed` are working fine, but your `/instagram/browser/post` requests are 400ing because Bridgy can't scrape your post permalinks' HTML.

The odd part is that `/instagram/browser/post` requests for other users are working fine, and they send the raw HTML from IG, so nothing different is happening in the browser extension or Bridgy backend. 🤔

**Comment by snarfed** [comment]
Also odd, I tried sending it the HTML I get from https://www.instagram.com/p/CXuwY4JLAGd/ , logged into my own account, and it scrapes fine. So your browser is getting something different.

I've instrumented it to store the raw HTML you send, we'll see what's in there.

**Comment by gRegorLove** [comment]
Aha, I have uBlock Origin running. I wonder if that's interfering. Let me try disabling that for Instagram briefly and report back.

**Comment by gRegorLove** [comment]
I was wrong, uBlock is not enabled on instagram.com, so I don't think that's it.

**Comment by snarfed** [comment]
Yup, they changed their HTML. Whee. Thanks for reporting!
