### ISSUE TITLE
Can't remove deleted Reddit account

### ISSUE THREAD

**Issue by toddgrotenhuis** [snarfed/bridgy#1103]
I tried these instructions to remove a deleted Reddit account, but all I could do is add my new reddit account, not remove my old one.

https://brid.gy/about#add-remove-url

**Comment by snarfed** [comment]
Hey Todd, sorry for the trouble! If the old account is deleted in Reddit, I assume that means you can't log into it any more? Bridgy expects you to auth as a given account to prove you own it before it will let you disable/remove it, so that won't work in this case. I'll just go ahead and disable it manually instead.

**Comment by toddgrotenhuis** [comment]
Correct, can't authenticate to that account that doesn't exist anymore.

Thank you!
