### ISSUE TITLE
Is it possible to be logged in with multiple social networks?

### ISSUE THREAD

**Issue by davidcelis** [snarfed/bridgy#1194]
I'm setting up brid.gy to publish posts from my own website (a micro.blog site) to both Twitter and Mastodon. From what I can tell, I need to sign into both Twitter and Mastodon separately to manage each one, but I figured I'd double check here in case I'm missing something. Is there an easier way to combine these accounts and essentially be logged into brid.gy for twitter, mastodon, and my own site all at once?

**Comment by snarfed** [comment]
Hi! That's right, you connect each silo to Bridgy separately, it doesn't currently have a way to "connect" your logins. That's a long standing feature request, #38, which I haven't implemented mostly because I haven't seen a real use case for it yet, other than maybe avoiding confusion. Do you know what you'd hope to do differently with Bridgy if it knew your Twitter and Mastodon accounts were the same person?

**Comment by davidcelis** [comment]
Not really, it would just make using brid.gy a little bit easier; I'd be able to monitor and look at my polling results and site crawls in a more consolidated way without having to sign out and sign back in to get a more complete picture. It's more of a minor inconvenience than a big issue, so if this is something that's gnarly to implement, I totally get that!

**Comment by snarfed** [comment]
Oh, you don't have to log out and back in! All user pages are publicly visible. Once you've connected an account, it sets a cookie to render a convenience link in the upper right that goes to your user page for that account. After that, logging in again doesn't do anything.
![Screenshot_20220508-134516.png](https://user-images.githubusercontent.com/778068/167315188-61105b54-8dbb-4677-a762-0ea489fd948c.png)

**Comment by snarfed** [comment]
No worries! And I'll actually keep this open until I add more docs around this.
