### ISSUE TITLE
Mastodon doesn't support type(s) h-card, or no content was found.

### ISSUE THREAD

**Issue by justincox** [snarfed/bridgy#1603]
I'm confused. Brid.gy is running and synced to my website. Mentions from Mastodon are showing in the Brid.gy dashboard, but they're reporting `no webmention targets`. I modified my site theme to include the h-card properties, which are validated by https://indiewebify.me. Yet, when I go back to brid.gy, I get the error: `Mastodon doesn't support type(s) h-card, or no content was found.` What am I doing wrong?

**Comment by snarfed** [comment]
Looks like it's sent at least a handful of webmentions! For example, the one currently at the top of https://brid.gy/mastodon/@justin@holonet.social . Sent 2023-11-06 20:48:47 UTC, source https://brid.gy/repost/mastodon/@justin@holonet.social/111335888674388137/110655994396525979, target https://justincox.com/blog/2023/11/write-now-with-lauren-roberts/ , to your webmention endpoint https://justincox.com/webmentions/receive/ , which returned HTTP 202.

I expect Bridgy didn't do anything for most of the other responses because it needs a way to connect each post on Mastodon to its corresponding post on your web site: https://brid.gy/about#link%20to%20your%20web%20site

**Comment by snarfed** [comment]
As for the `doesn't support type(s) h-card` error, it sounds like you were entering your site into the publish form. [That cross-posts from your site _to_ Mastodon](https://brid.gy/about#publishing), while backfeed sends replies, likes, reposts etc from Mastodon back to your site. Separate features.

Sorry for the confusion. Happy to answer any other q's!

**Comment by snarfed** [comment]
It's not enough for your Mastodon profile to link to your web site or vice versa. Bridgy needs to know which specific post on your site matches which specific post on Mastodon. You can do that for each post either by including a link inside a Mastodon post to the original post on your site, or by including [syndication links](https://indieweb.org/u-syndication) on the original post that point to the Mastodon copy. The link I posted has more details.

**Comment by snarfed** [comment]
Welcome! Tentatively closing.
