### ISSUE TITLE
Support Facebook Pages

### ISSUE THREAD

**Issue by jaschaurbach** [snarfed/bridgy#1637]
Hi!

I only post on my Facebook Page, nearly never on my private profile.

Can we somehiow get support to scrape Facebook pages?

**Comment by snarfed** [comment]
Hi! The short answer is, it's unlikely. Sorry for the bad news.

Bridgy has a long history of Facebook support. It was [included at launch way back in 2012](https://brid.gy/about#history). Facebook later [removed the APIs we needed, so we had to shut it down](https://brid.gy/about#rip-facebook). We later [added it back with scraping and a browser extension](https://brid.gy/about#browser-extension), which I somewhat regret, since maintaining scraping over time is always painful, but it is at least still working.

I'm not optimistic about the future of the browser extension or its scraping, but I'm happy to help if you want to dive in and add Pages support!

**Comment by jaschaurbach** [comment]
If I could do such things I would great full help doing it but I am just a bad coder :/
