### ISSUE TITLE
Short URLs

### ISSUE THREAD

**Issue by pfefferle** [snarfed/bridgy#173]
What do you think about using [rel-shortlink](http://microformats.org/wiki/rel-shortlink) for twitter-syndication?

**Comment by snarfed** [comment]
sounds like @singpolyma would like this too (#422).

@singpolyma, out of curiosity, what's your use case for short urls? i'm always curious since twitter now t.co-wraps all links, so their length no longer matters, and no other supported silos limit chars.

btw, you can currently get bridgy to use a short link when publishing if you put the short link into the interactive UI instead of the full link, or use it as the `source` param if you're webmentioning. https://www.brid.gy/about#short-link

**Comment by singpolyma** [comment]
It's about visual noise.  If I post "it sure is hot outside" then a Facebook post like:

    it sure is hot outside
    
    (Original Link: https://singpolyma.net/2015/06/it-sure-is-hot-outside)

Just looks excessive...

Also, on twitter, I use algorithmic shorturls that I would prefer be displayed rather than t.co links (though of course it will be wrapped in t.co underneath in official clients)

**Comment by dissolve** [comment]
I think this is a good idea, it may not be too easy to send the shortlink in the webmention in your system.

**Comment by snarfed** [comment]
note to myself: i think i can find the shortlink(s) in a page with just:
```
soup.find_all('link', rel='shortlink') +
  soup.find_all('a', rel='shortlink') +
  soup.find_all('a', class='shortlink')
```

**Comment by snarfed** [comment]
quick survey! [rel-shortlink](http://microformats.org/wiki/rel-shortlink), which @pfefferle mentioned, is evidently the standard (or close enough).

looking at recent posts from the three people who requested this:

@pfefferle has:
* `<link rel="shortlink">` in head
* `<input class="shortlink" value="[URL]">` in body

@singpolyma has:
* `<link rel="shorter short_url">` in head

@dissolve has:
* `<a rel="shortlink" class="shortlink u-shortlink">` in body

looks like `shortlink` is the winner. sorry @singpolyma! you'll want to update your markup if you still want to use this feature.

**Comment by kylewm** [comment]
class="shortlink" is hAtom/mf1, and we should probably add it to
backcompat parsing of mf2py instead of to Bridgy.


On Thu, Sep 17, 2015, at 08:54 AM, Ryan Barrett wrote:
> quick survey! rel-shortlink[1], which @pfefferle[2] mentioned, is
> evidently the standard (or close enough).


> looking at recent posts from the three people who requested this:


> @pfefferle[3] has:


>  * <link rel="shortlink"> in head
>  * <input class="shortlink" value="[URL]"> in body @singpolyma[4] has:


>  * <link rel="shorter short_url"> in head @dissolve[5] has:


>  * <a rel="shortlink" class="shortlink u-shortlink"> in body looks
>    like shortlink is the winner. sorry @singpolyma[6]! you'll want to
>    update your markup if you still want to use this feature.


>


> — Reply to this email directly or view it on GitHub[7].
>


>



Links:

  1. http://microformats.org/wiki/rel-shortlink
  2. https://github.com/pfefferle
  3. https://github.com/pfefferle
  4. https://github.com/singpolyma
  5. https://github.com/dissolve
  6. https://github.com/singpolyma
  7. https://github.com/snarfed/bridgy/issues/173#issuecomment-141130389

**Comment by snarfed** [comment]
evidently the way to get a feature into bridgy is to have three different people ask for it. :P
