### ISSUE TITLE
Received a brid.gy webmention from a Mastodon comment that was in reply to the one that actually linked to my post

### ISSUE THREAD

**Issue by Oblomov** [snarfed/bridgy#1838]
Hello all, I've recently adding experimental support for webmention on my website, and I've only received one so far, from brid.gy. However, the `source` redirects to a Mastodon comment that is apparently _not_ the one that actually links to a page on my website, but a comment in reply to it.

`target`: https://wok.oblomov.eu/tecnologia/credible-threat-2/

`source`: https://brid.gy/comment/mastodon/@cybeardjm@masto.ai/113432923029140253/113432947618109928

Is this expected?

**Comment by snarfed** [comment]
Interesting! You're right, that's not ideal, but it does happen occasionally. It's surprisingly complicated to navigate all the different threads and paths through them to determine exactly the right set of webmention targets for a given reply or other interaction. Bridgy is pretty good at it at this point, but when things get complicated, it defaults to being "promiscuous," ie it errs on the side of sending too many webmentions, rather than too few and possibly missing one.

In this case, since threads are common on Mastodon etc, and this was from the same author as the original post that linked to you, Bridgy interprets it as a follow-up that should probably be included with the original. To that end, it includes a `u-in-reply-to` link to the original post, and only a `u-mention-of` link to your web page.

Still complicated, I know. Sorry for the confusion!

**Comment by Oblomov** [comment]
No problem. The weird thing is that I'm not seeing a webmention for the original comment, although that might be because I was still working on the implementation on my side when the comment was written so I missed it. We can close this issue for me, unless you'd prefer to keep it open for reference.
