### ISSUE TITLE
twitter: extract actor URLs from profile description

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#322]
e.g. http://ampoliros.net/ in https://twitter.com/hugoroyd.

inspired by @hugoroy, idno/idno#633, https://indiewebcamp.com/irc/2014-12-17#t1418831157060

**Comment by mapkyca** [comment]
Just noting this here: I notice that the tweetdeck entry for a post from Known showed the app name as source, with an app URL (presumably because when I registered the app I entered my website). 

It's not on the same entry on the website, but presumably it's getting this from somewhere, presumably source information is returned as part of the API query. 

Might be another option to extract the base site to parse for post links...
