### ISSUE TITLE
publish: support POSSE like to Instagram

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#326]
if I post a "like" of an Instagram photo (with a u-like-of link to an Instagram photo permalink), it would be great if I could call Bridgy Publish to POSSE that like to my account on Instagram.

**Comment by snarfed** [comment]
tentatively bumping to _now_. i don't plan to jump on it myself in the near future, but theoretically we should only need to implement the instagram API part, and flip a handful of switches elsewhere, and the rest should Just Work.

**Comment by kylewm** [comment]
can you fill me in on the background here -- 

https://github.com/snarfed/python-instagram is a fork of
https://github.com/mgunneras/python-instagram which is a fork of
https://github.com/Instagram/python-instagram

but it seems the latter two have diverged non-trivially. If I want a change from the Instagram/python-instagram fork, should I just export it as a diff and apply it manually?

**Comment by snarfed** [comment]
thanks again for tackling this! ugh, yeah, the libs. you're right, nontrivial skew btw all three. manual patch is probably the best route...but honestly i'd love to drop the lib and just use the REST API directly. that's obviously scope creep for this, but i'm totally open to it! either one sgtm.

**Comment by kylewm** [comment]
cool, I agree it would be nice to pull out the lib and I'm happy to tackle that.

**Comment by kylewm** [comment]
Question: When a token is revoked, Instagram replies with status code 400 and error_type=OAuthAccessTokenException. `interpret_http_exception` catches this particular case and [changes the code to 401](https://github.com/snarfed/oauth-dropins/blob/d504d6bec799d499c0b5b60133b0ed03bfcfccad/handlers.py#L198) 

This is important because later on [Bridgy gets the 401](https://github.com/snarfed/bridgy/blob/master/tasks.py#L177) and disables the source.

Should I do basically the same thing in interpret_http_exception now that it's a regular urllib2.HTTPError instead of the special InstagramAPIError? i.e. check for 'OAuthAccessTokenException' and 'APIRequiresAuthenticationError' in the body of the error message and give 401 as the error code? 

Thanks!

**Comment by snarfed** [comment]
yup, good call, that's exactly what we'd want to do. thanks!

**Comment by snarfed** [comment]
yay, launched! example: https://snarfed.org/2015-01-08_photo-by-thejohnnysmith-2

@kylewm, i'll let you do the honor of closing this. :P
