### ISSUE TITLE
Twitter reply generates mf2 with a wrong URL as "u-in-reply-to"

### ISSUE THREAD

**Issue by fiatjaf** [snarfed/bridgy#369]
I don't know how to phrase this exactly.

Here's the problem: https://brid-gy.appspot.com/comment/twitter/fiatjaf/571490641902845952/571669729833840640 (look at the source)
Also here (found this link while searching for similar issues in this repo): https://brid-gy.appspot.com/comment/twitter/kartik_prabhu/459519287992930304/480518663985197056

Here's an extract of the HTML generated by bridgy:

```html
  <div class="e-content p-name">
  
  <a href="https://twitter.com/fiatjaf">@fiatjaf</a> pam!
<a class="u-mention" href="http://fiatjaf.alhur.es/trens/socrates-homofobico/"></a>
  </div>



  <a class="u-in-reply-to" href="http://fiatjaf.alhur.es/trens/socrates…"></a>
```

So, the HTML has the correct URL at the `u-mention` tag, but a bizarrely shortened URL (that doesn't work, let's make it clear) at the `u-in-reply-to` tag. This, I imagine, causes bridgy to send two webmention from the same tweet, but one of them with the wrong URL as `target`.

(my server, however, accepts both webmentions, because it finds the `u-mention` URL to be correct, and this causes me a small trouble.)

**Comment by kylewm** [comment]
Thanks for the report @fiatjaf, and sorry for the trouble! I'm on the case.

@snarfed a-u searches the post content for a permashortcitation, and this text is a match `(fiatjaf.alhur.es/trens/socrates…)`.

**Comment by snarfed** [comment]
nice sleuthing, guys! @kylewm makes sense. sounds like an easy fix would be to not allow PSCs that end in ellipses, either the dots or the unicode char.

**Comment by kylewm** [comment]
I think that would work. Alternatively I was wondering what you think about replacing t.co links with `expanded_url` instead of `display_url`, i.e. here https://github.com/snarfed/activitystreams-unofficial/blob/master/twitter.py#L895

So the content of the note would actually be 

`S\u00f3crates, o homof\u00f3bico\nTrechos de epis\u00f3dios da Memorabilia, ou os Ditos e Feitos Memor\u00e1veis de S\u00f3crates, contados\u2026 (http://fiatjaf.alhur.es/trens/socrates-homofobico/)`

In that case *no* permalink would match the permashortcitation regex e.g. `(bit.ly abcd)` would match but `(http://bit.ly/abcd)` wouldn't

I don't have a preference one way or the other, and checking for ellipsis is a much smaller change.

**Comment by snarfed** [comment]
interesting! we actually do include expanded_url further down, in tags instead of content, so that we can render it nicely in HTML (or whatever) with the pretty display URL linked to the full expanded URL. that seems to be the standard pattern in AS, FB, and Twitter at least.

I think I'd like to keep that behavior, so I vote we detect trailing ellipses instead.

the next question is, do we need to do that in webutil.util.extract_links, or the PSL code, or both? no clue.

**Comment by snarfed** [comment]
yay thanks @kylewm!
