### ISSUE TITLE
Facebook app-scoped user ids break posse-post-discovery

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#375]
This only applies to Bridgy accounts created after the switch to the 2.0 API.

Bridgy gets a list of my posts, e.g. 

  `https://www.facebook.com/[app-scoped user id]/posts/10101237953173839`

Checks my homepage h-feed and finds a post that connects to 

  `https://www.facebook.com/[global user id]/posts/10101237953173839`

which will never match each other. Really ppd already didn't work super great for Facebook because they serve the same content at several different URLs (substituting username for id for example), and u-syndication could point to any of them.

Just thinking about this, I haven't actually encountered it yet that I know of.

**Comment by snarfed** [comment]
huh. true! great point. and i don't really see a way around it either. facebook support continues to crumble day by day. :/ cc #350

we actually try pretty hard to [handle many varieties of facebook post URLs](https://github.com/snarfed/bridgy/blob/master/facebook.py#L208), including photos and username vs ids, but it's an arms race that we obviously can't invest in as heavily as they can. ah well. :P

**Comment by nekr0z** [comment]
Mmm... This may be why I have yet to see Bridgy detect any replies or likes on my Facebook.

**Comment by kylewm** [comment]
@nekr0z this shouldn't affect you. Your Facebook posts have a "See Original" link at the bottom, so the posse-post discovery fallback mechanism shouldn't come into play.

I just looked, and Bridgy somehow does not have the "user_posts" permission for your account. I know you just revoked and reauthorized a couple days ago, would you mind trying again (You should just be able to click the Facebook button on https://brid.gy). When I do it, it prompts me for the permissions "Bridgy will receive the following info: your News Feed, status updates, events, photos and website.". Double check that you are seeing the same?

**Comment by nekr0z** [comment]
@kylewm I've just re-wired Bridgy with Facebook again. In my case upon reauthorization the info about permission was in Russian, so no use in including it verbatim, but itonly mentioned public profile and website, and didn't mention updates, photos or events.

**Comment by snarfed** [comment]
FB has now auto-assigned usernames to all users, and it redirects post URLs  in the browser to always use username instead of user id (whether global or app-scoped). due to that, we started inferring FB usernames in #447/#448, which is currently working well.

that should handle syndication URLs that are copy/pasted into a CMS by users. for posts that are  POSSEd programmatically, [FB just returns the post id](https://developers.facebook.com/docs/graph-api/reference/v2.5/user/feed#pubresponse), so if any CMSes are constructing FB post URLs with user id instead of username, i guess we can lean on them to switch.

(there are also URLs that don't use user id *or* username, e.g. `/photo.php?fbid=...` and `/story.php?story_fbid=...`, but those don't have this problem in the first place.)

so, given all that, i think we can close this. if anyone disagrees, feel free to reopen!

**Comment by kylewm** [comment]
> , so if any CMSes are constructing FB syndication URLs with user id instead of username, i guess we can lean on them to switch.

[I am](https://github.com/kylewm/redwind/blob/master/redwind/plugins/facebook.py#L248) apparently!

**Comment by snarfed** [comment]
ahahahahahahaha

...but you didn't hit the bug because you authed both the bridgy and redwind FB apps before api v2.0, so both of them have your global user id. (you successfully get backfeed from FB, e.g. https://kylewm.com/2015/10/reading-https-en-wikipedia-org-wiki-steganography )

**Comment by kylewm** [comment]
Cool that makes sense.

FWIW, Bridgy Publish [uses user id too](https://github.com/snarfed/granary/blob/master/granary/facebook.py#L601)... 

It turns out I don't really know the right way to get a post permalink from the ID the API returns! Part of Facebook's war on URLs.

**Comment by kylewm** [comment]
> FB has now auto-assigned usernames to all users, and it redirects post URLs in the browser to always use username instead of user id (whether global or app-scoped)

As far as I can tell, it does not redirect anymore, whether logged in or out, e.g. https://www.facebook.com/12802152/posts/10101645114169939 ... They probably realized this was a leak and plugged it.

So I don't think there is a good way to determine the username of a user... Known's FB plugin cannot do it; silo.pub has a configuration option where you can manually enter your username. 

I'd like to explore the possibility of expanding `inferred_username` to include inferred usernames and possibly many inferred user IDs.

**Comment by snarfed** [comment]
sure! i've noticed the same decrease in redirecting, btw. maybe i overstated it originally; not sure.

regardless, inferring user ids sgtm. we'll see some edge cases with people who have FB pages and bleed their posseing across their user and the page, but shouldn't be a big problem, and I'm fine if we start out simple and dumb and handle those if/when we see them.

I'd probably lean toward a new `inferred_user_ids` field instead of overloading `inferred_username`, but I'm probably getting ahead of myself. thanks for looking into this!

**Comment by snarfed** [comment]
(related discussion in #650)

**Comment by snarfed** [comment]
so @kylewm now that we infer both usernames and user ids, do you think we should close this?

**Comment by kylewm** [comment]
I do! Thanks for the reminder, I'd intended to close it as soon as we confirmed it worked.
