### ISSUE TITLE
handle FB error "user is not a confirmed user"

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#436]
curently getting this error for [10153013291712807](https://www.brid.gy/facebook/10153013291712807). [fb api docs.](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.0#errorsubcodes) probably just need to disable them.

[example log](https://www.brid.gy/log?start_time=1438623958&key=aglzfmJyaWQtZ3lyIwsSDEZhY2Vib29rUGFnZSIRMTAxNTMwMTMyOTE3MTI4MDcM):

```
Fetching https://graph.facebook.com/v2.2/me/posts?offset=0&limit=50&access_token=...... kwargs {'headers': {'If-None-Match': u'"37a621f8edbe450f611c54900ba0beb320177ffc"'}}
Error 400, response body: {
"error":{
  "message":"Error validating access token: ... for the user are not allowed because the user is not a confirmed user.",
  "type":"OAuthException",
  "code":190,
  "error_subcode":464
}}
2015-08-03 17:45:58.364420 E HTTP Error 400: Bad Request
Traceback (most recent call last):
...
File "/base/data/home/apps/s~brid-gy/3.386141412475663659/tasks.py", line 109, in post
source_updates.update(self.poll(source))
File "/base/data/home/apps/s~brid-gy/3.386141412475663659/tasks.py", line 161, in poll
cache=cache)
File "/base/data/home/apps/s~brid-gy/3.386141412475663659/facebook.py", line 107, in get_activities_response
resp = self.gr_source.get_activities_response(group_id=SELF, **kwargs)
File "/base/data/home/apps/s~brid-gy/3.386141412475663659/local/lib/python2.7/site-packages/granary/facebook.py", line 226, in get_activities_response
resp = self.urlopen(url, headers=headers, parse_response=False)
File "/base/data/home/apps/s~brid-gy/3.386141412475663659/local/lib/python2.7/site-packages/granary/facebook.py", line 1225, in urlopen
timeout=appengine_config.HTTP_TIMEOUT)
...
HTTPError: HTTP Error 400: Bad Request
```

**Comment by kylewm** [comment]
It seems like he doesn't have a Facebook account anymore?


On Mon, Aug 3, 2015, at 11:09 AM, Ryan Barrett wrote:
> curently getting this error for 10153013291712807[1]. fb api docs.[2]
> probably just need to disable them.


> example log[3]:


> Fetching
> https://graph.facebook.com/v2.2/me/posts?offset=0&limit=50&access_token=......
> kwargs {'headers': {'If-None-Match':
> u'"37a621f8edbe450f611c54900ba0beb320177ffc"'}}
Error 400, response body: { "error":{  "message":"Error validating
access token: ... for the user are not allowed because the user is not a
confirmed user.",  "type":"OAuthException",  "code":190,
"error_subcode":464 }} 2015-08-03 17:45:58.364420 E HTTP Error 400: Bad
Request Traceback (most recent call last): ... File "/base/data/home/apps/s~brid-
gy/3.386141412475663659/tasks.py", line 109, in post
source_updates.update(self.poll(source)) File "/base/data/home/apps/s~brid-
gy/3.386141412475663659/tasks.py", line 161, in poll cache=cache) File
"/base/data/home/apps/s~brid-gy/3.386141412475663659/facebook.py", line
107, in get_activities_response resp =
self.gr_source.get_activities_response(group_id=SELF, **kwargs) File "/base/data/home/apps/s~brid-
gy/3.386141412475663659/local/lib/python2.7/site-
packages/granary/facebook.py", line 226, in get_activities_response resp
= self.urlopen(url, headers=headers, parse_response=False) File "/base/data/home/apps/s~brid-
gy/3.386141412475663659/local/lib/python2.7/site-
packages/granary/facebook.py", line 1225, in urlopen
timeout=appengine_config.HTTP_TIMEOUT) ... HTTPError: HTTP Error 400:
Bad Request
>
> — Reply to this email directly or view it on GitHub[4].


>



Links:

  1. https://www.brid.gy/facebook/10153013291712807
  2. https://developers.facebook.com/docs/graph-api/using-graph-api/v2.0#errorsubcodes
  3. https://www.brid.gy/log?start_time=1438623958&key=aglzfmJyaWQtZ3lyIwsSDEZhY2Vib29rUGFnZSIRMTAxNTMwMTMyOTE3MTI4MDcM
  4. https://github.com/snarfed/bridgy/issues/436

**Comment by snarfed** [comment]
i guess "not confirmed" is one way to describe that. :package:
