### ISSUE TITLE
Include dt-published consistently

### ISSUE THREAD

**Issue by csarven** [snarfed/bridgy#441]
Use `dt-published` in bridgy's Webmention URL e.g., https://brid-gy.appspot.com/like/twitter/csarven/630394109363126273/21281499 . If the originating service doesn't provide one, generate it yourself and include that.

Consequently, this will better preserve the chronological order of the events.

**Comment by rhiaro** [comment]
+1

**Comment by snarfed** [comment]
hey, thanks for the feedback! you guessed right; bridgy omits `dt-published` when the silos themselves don't provide it, e.g. for twitter favorites and facebook likes.

this was an intentional descision. `dt-published` is optional [as are all mf2 properties](http://microformats.org/wiki/microformats2#microformats2_design), and i was uncomfortable generating it when i knew i'd sometimes get it wrong. for example, when you first sign up, bridgy looks at your last N posts and all of their responses, which could be arbitrarily long ago. same thing if you revoke your access token or it expires (e.g. facebook), and then sign up again later.

i'm definitely with you on preserving the chronological order of all responses. in practice, bridgy polls every ~15m or so, so rough order is usually still preserved.

more feedback is welcome!

**Comment by csarven** [comment]
Acknowledged. It was just a heads up. I brought it up because I create `dt-published` if it is not provided. I think if you stick to UTC 0 in everything (on first glance, it seems that you are), it'll be easier to handle.

PS: the properties being optional in mf2 is a good thing. It employs the _open-world assumption_ - also common in publishing Linked Data or knowledge representation in Semantic Web.

**Comment by RehanSaeed** [comment]
Is there any particular reason why Twitter favourites are missing `published` and `published_ts` from the API but we get them for reposts?

**Comment by snarfed** [comment]
@RehanSaeed yes! Twitter doesn't have an API for favorites, so we have to scrape them from the web, which doesn't include their timestamps. Reposts (ie retweets), on the other hand, we do get from the API, which does include timestamps.

**Comment by Ryuno-Ki** [comment]
![facepalm](https://media.giphy.com/media/bkklBjAmlYjv2/giphy.gif)
