### ISSUE TITLE
SSL verification failing, maybe missing SNI support

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#442]
According to https://www.ssllabs.com/ssltest/analyze.html?d=peterwilson.cc this certificate is valid but only works on older protocols and requires SNI.

```
2015-08-10 21:38:22.974

Could not fetch author url https://peterwilson.cc
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/original_post_discovery.py", line 183, in _process_author
    author_resp = util.requests_get(author_url)
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/util.py", line 108, in requests_get
    return requests.get(url, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/local/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386338618119190445/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:529: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

cc @peterwilsoncc

**Comment by snarfed** [comment]
hrm. @aaronpk noticed this happened to him today or yesterday too.

i inadvertently changed and pushed some of our deps recently. i thought i fixed them all, but i suspect that's the cause. hey @kylewm, when you get a chance, would you mind pulling master and push with your deps to see if that fixes it? if it does, I'll fix my local deps.

**Comment by snarfed** [comment]
@kylewm pushed (thanks!) but it didn't fix this. looks like we're failing SSL verification on some sites, maybe since we (now?) don't support SNI well or at all. :(

**Comment by aaronpk** [comment]
What would have changed in Bridgy? My site has always used SNI.

**Comment by snarfed** [comment]
@aaronpk agreed, it was probably a change on our end. we don't know what, but we'll find out!

**Comment by snarfed** [comment]
notably, the urllib3 warning in [`this propagate log`](https://www.brid.gy/log?start_time=1439309464&key=aglzfmJyaWQtZ3lySwsSCFJlc3BvbnNlIj10YWc6ZmFjZWJvb2suY29tLDIwMTM6MTU5ODI2NDY3MDQzODU2Ml9yc3ZwXzEwMTU1MDg0MzE3ODM1MDA2DA) is suspicious because ideally we don't want to use urllib3 at all, due to e.g. #396.

```
I Webmention from https://brid-gy.appspot.com/rsvp/facebook/688447421193285/1598264670438562/10155084317835006 to https://kylewm.com/2015/08/homebrew-website-club
I Using cached webmention endpoint for kylewm.com: https://kylewm.com/webmention
I Sending...
I Starting new HTTPS connection (1): kylewm.com
E /base/data/home/apps/s~brid-gy/3.386360013069944042/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
E InsecureRequestWarning)
D "POST /webmention HTTP/1.1" 202 None
I Sent! {'body': u'<!DOCTYPE html>\n<html>\n <head>\n <meta charset="utf-8">\n </head>\n <body>\n <h1>Webmention Received</h1>\n <p>Thanks! Ths webmention has been queued for processing.</p>\n <p>Check status: <a rel="status" href="https://kylewm.com/webmention/status/e23d294e-0069-4365-81ee-054c87f11e8b">kylewm.com/webmention/status/e23d294e-0069-4365-81ee-054c87f11e8b</a>.</p>;\n <p><a href="/">Return to site</a>.\n </p>\n </body>\n</html>', 'request': u'POST https://kylewm.com/webmention (with source=https://brid-gy.appspot.com/rsvp/facebook/688447421193285/1598264670438562/10155084317835006, target=https://kylewm.com/2015/08/homebrew-website-club)', 'http_status': 202}
I Setting last_webmention_sent
```

**Comment by snarfed** [comment]
[example poll log](https://www.brid.gy/log?start_time=1439309249&key=aglzfmJyaWQtZ3lyGgsSDEZhY2Vib29rUGFnZSIIMTI4MDIxNTIM) from [@kylewm's facebook account](https://www.brid.gy/facebook/12802152). this one doesn't have the urllib3 warning, but shows failed verification due to cert hostname not matching. kyle's site uses SNI too, which is the clue to what's (now) tripping us up.

```
D fetching author url https://kylewm.com
I Starting new HTTPS connection (1): kylewm.com
W Could not fetch author url https://kylewm.com
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/3.386360013069944042/original_post_discovery.py", line 183, in _process_author
  author_resp = util.requests_get(author_url)
File "/base/data/home/apps/s~brid-gy/3.386360013069944042/util.py", line 108, in requests_get
  return requests.get(url, **kwargs)
...
File "/base/data/home/apps/s~brid-gy/3.386360013069944042/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
  raise SSLError(e, request=request)
SSLError: hostname 'kylewm.com' doesn't match either of 'www.silo.pub', 'silo.pub'
```

**Comment by snarfed** [comment]
fwiw, there aren't any relevant recent threads about SSL on the app engine mailing list. https://groups.google.com/forum/#!searchin/google-appengine/ssl|sort:date

**Comment by snarfed** [comment]
[the earliest `SSLError` i can find in the logs](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=text:SSLError&lastVisibleOffset=55c62efa00ff0c172f27535cf30001737e627269642d67790001330001010f&lastVisibleTimestampNanos=1439051516490000000) is 2015-08-08 8:18am PST. looking at the [admin deploy logs](https://appengine.google.com/adminlogs?tz=US%2FPacific&app_id=s~brid-gy&type=version_updated&limit=50), we deploy pretty often, every 1-2d, but i did deploy at 8:16am that same day, and once the `SSLError`s started, they happened every ~5-10m, so that deploy was likely the culprit.

**Comment by snarfed** [comment]
the last successful deploy before that bad one was 2015-08-07 10:38pm PST. i pulled a backup of my local bridgy client from before then, around 2015-08-07 9am, and diffed the directory trees.

the symlinks in `local/lib/python2.7/site-packages/` to local repos for granary, oauth-dropins, and webmentiontools are the same.

the output from `pip list` _should_ be the same, but the old client prints a bunch of other packages that i think are coming from the system, not the virtualenv. not sure why that is, especially since `pip list --local` still prints them. it looks like pip isn't installed in the old virtualenv, so it's running the system's. weird.

ignoring that, looking at the actual files themselves, here's the diff of ``local/lib/python2.7/site-packages/`:
```diff
7a18
 html5lib-0.999-py2.7.egg-info/
8a30
 oauthlib-1.0.1-py2.7.egg-info/
0c32
 pip-6.0.8.dist-info/
--
 pip-7.1.0.dist-info/
8c40
 requests-2.1.0.dist-info/
--
 requests-2.5.3.dist-info/
9a42
 requests_oauthlib-0.5.0.dist-info/
6a50
 six.py
```

**Comment by snarfed** [comment]
sadly, my current (bad) local client doesn't repro the `SSLError`s, so it's hard to verify a fix without deploying. ah well.

**Comment by snarfed** [comment]
i ran `pip install requests==2.1.0; pip uninstall html5lib` in my current (bad) local client, and i'm deploying now. fingers crossed.

**Comment by snarfed** [comment]
woot, looks like that fixed it. [example log of OPD happily fetching https://kylewm.com again.](https://www.brid.gy/log?start_time=1439333865&key=aglzfmJyaWQtZ3lyGgsSDEZhY2Vib29rUGFnZSIIMTI4MDIxNTIM)

sad that we require requests 2.1.0 though. ¯\\\_(ツ)_/¯
