### ISSUE TITLE
No post links found?

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#470]
Not entirely sure when it started, but it looks like bridgy is not recognising links in Twitter and G+ posts for me at the moment (for a change FB seems to be OK, which must be a first....).
Accounts are:
https://www.brid.gy/twitter/islayblog
https://www.brid.gy/googleplus/111306950318319005217

Interesting in particular this tweet: https://twitter.com/islayblog/status/642608209635708928
Here the link was originally found (and the webmention sent), but on a later favourite it now says "No post links found"

Also this G+ post is strange: https://plus.google.com/+ArminGrewe/posts/PwjuxhjPetH
For the most recent "+" (from Nigel Brown) it says "No post links found", however, for his comment and my reply it found the link and sent the mention.

**Comment by snarfed** [comment]
thanks for the report! this is likely due to the changes we've been making for #51. i'll look into it.

**Comment by snarfed** [comment]
@armingrewe looks like this is because you don't have all of your web sites in your G+ and twitter profiles. #51 tightens which links we interpret as "original post" links, and one of the ways we do that is to limit to just the web sites in your profile, if any. try adding the rest of your sites to your profiles, then re-login with them on bridgy?

we're keeping #51 open for feedback, and i'll make a note of this there. still open to debate.

**Comment by armingrewe** [comment]
Let's close it here and follow up in #51 (posted my update there)
