### ISSUE TITLE
Flickr should respect privacy settings

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#477]
Every photo has a `{"ispublic": 1 or 0}`, we need to respect this and not backfeed likes and comments on private photos.

Thanks @snarfed for the catch, I'd completely forgotten that Flickr even has non-public photos :P

**Comment by snarfed** [comment]
thanks! also i assume comments/likes inherit the post's privacy setting, similar to FB, IG, G+? i have no idea how it would work otherwise, but just checking. (i think actually twitter works differently somehow; i definitely have no idea how @-replies to protected twitter accounts work. ah well. :P)

**Comment by kylewm** [comment]
Yes, that's correct.

**Comment by kylewm** [comment]
I think this should be enough https://github.com/snarfed/granary/commit/c0ad04c6db42a611b09e86997d523df6e5058720

**Comment by snarfed** [comment]
lgtm, thanks!
