### ISSUE TITLE
Automatically create twitter hashtags from tags

### ISSUE THREAD

**Issue by cweiske** [snarfed/bridgy#478]
POSSEing articles to twitter should automatically append hashtags for the tags used on the article.

An article "Hello world", tagged with `first` and `test` should get a twitter line "Hello world #first #test".

When the tag is already part of the title, the word should be converted to a hashtag:

"Playing Tomb Raider 1 on OUYA" should get tweeted as "Playing Tomb Raider 1 on #OUYA" when it was tagged with "ouya".

**Comment by snarfed** [comment]
thanks for filing!

example post: http://cweiske.de/tagebuch/ouya-tomb-raider.htm

parsed as mf2 (https://kylewm.com/services/mf2?url=http://cweiske.de/tagebuch/ouya-tomb-raider.htm):

```json
{"items": [{
  "type": ["h-entry"],
  "properties": {
    "category": ["bigsuck", "games", "ouya"],
    "name": ["Playing Tomb Raider 1 on OUYA"],
...
```

ideally we'd look at the categories, hashtag the ones in the title in place, ignoring case, and append the rest. something like:
> Playing Tomb Raider 1 on #OUYA  [#bigsuck #games]

**Comment by anm** [comment]
I would prefer it to not tag the words if previously used, but just put all the tags at the end, because it looks nicer. If you want to complicate it though, you could still do it if the tweet is too big otherwise.

**Comment by Cambridgeport90** [comment]
I definitely think this should be a thing, as well. I am right now having to use other services at the moment in order to make this work.

**Comment by fundor333** [comment]
Any update on this? I love to have tags in my tweet and toot

**Comment by snarfed** [comment]
I'm not actively working on this, but I'd happily accept a PR! It'd probably go into granary. Not trivial, but should be doable!

**Comment by fundor333** [comment]
1) Is granary read only? For I can understand you can only read with granary you can't tweet or toot with it
2) My idea is use the p-category as the tags for the tweet/toot. Any suggestions for this?

If i have time I love to make a PR with this feature

**Comment by snarfed** [comment]
granary is definitely read/write! Bridgy Publish uses it to create tweets via the API. And yes, `p-category` is the idea, following the examples in the first two comments above. Thanks for offering to help!

**Comment by jamietanna** [comment]
I guess also to clarify there's Granary the library (read/write) and Granary the service (read-only?)

**Comment by snarfed** [comment]
Ah, yes, true! The API is read only. Bridgy uses the library, not the API.

**Comment by snarfed** [comment]
Thinking more about this now, since @fundor333 is offering to implement it in snarfed/granary#416. I'm open to it, but I'm not sure it should be the default behavior, which implies that we'd add another option for it, which I'm allergic to due to [Keep Bridgy Publish dumb](https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb).

Everyone who's expressed interest here, @cweiske @Cambridgeport90 @anm @fundor333 et al, have you all considered Bridgy's existing [`p-bridgy-twitter-content`](https://brid.gy/about#silo-content) (and `p-bridgy-mastodon-content`, etc) feature? It lets you specify the exact text that Bridgy should tweet/toot/etc for a given post. You could auto-generate it for every post based on your post title and categories.

If this wouldn't work for you, mind posting details as to why not? Totally ok, I'm just curious.

**Comment by Cambridgeport90** [comment]
That would've worked really great somehow had I known those features even existed. I didn't even know, somehow it got missed, and I'm not particular sure how. But how do you actually use it then, is the question.

**Comment by snarfed** [comment]
No worries! Check out the docs, https://brid.gy/about#silo-content, and let me know if you have any questions.

**Comment by jamietanna** [comment]
https://www.jvt.me/mf2/2022/08/opz5y/ is an example of a post with silo-dependent content, if that's helpful, too

**Comment by snarfed** [comment]
Revisiting this now, I think https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb is the answer here. Condolences all! Tentatively closing.
