### ISSUE TITLE
Facebook "singular statuses API is deprecated for versions v2.4 and higher"

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#496]
I saw a foreboding error in the 2.4 API just now. Digging into this post:

https://brid-gy.appspot.com/post/facebook/987100564687701/996189387112152

I went to /v2.4/996189387112152 in the graph explorer and got this error message

```
{
  "error": {
    "message": "(#12) singular statuses API is deprecated for versions v2.4 and higher",
    "type": "OAuthException",
    "code": 12,
    "fbtrace_id": "BCVNMo7G4yt"
  }
}
```

I don't see anything about singular statuses being deprecated in [the changelog](https://developers.facebook.com/docs/apps/changelog). The ubiquitous [CBroe on StackOverflow suggests](http://stackoverflow.com/questions/31353591/how-should-we-retrieve-an-individual-post-now-that-post-id-is-deprecated-in-v) that posts should now be fetched with USERID_POSTID, but /v2.4/987100564687701_996189387112152 gives the even less helpful

```
{
  "error": {
    "message": "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
    "type": "GraphMethodException",
    "code": 100,
    "fbtrace_id": "C05nKNVH9n+"
  }
}
```

**Comment by snarfed** [comment]
man. has anything given us more trouble with bridgy than Facebook ids?! sigh. :P

thanks for filling so we can keep track!

**Comment by snarfed** [comment]
turns out this may not be as scary as we thought. afaict it weighs find when you include the USERID_ prefix in the post id. (phew!)

**Comment by nelson-temporal** [comment]
Hi guys, this still seems happen on 2.9 on posts pages I manage.
I'm currently using this code to get reactions on each post:

/v2.9/{POSTID}?fields=reactions.type(LOVE).limit(0).summary(total_count).as(love),reactions.type(LIKE).limit(0).summary(total_count).as(like),reactions.type(WOW).limit(0).summary(total_count).as(wow),reactions.type(HAHA).limit(0).summary(total_count).as(haha),reactions.type(SAD).limit(0).summary(total_count).as(sad),reactions.type(ANGRY).limit(0).summary(total_count).as(angry),reactions.type(THANKFUL).limit(0).summary(total_count).as(thankful)

On some posts on my own page I may need to my social id to make it work (e.g {SOCIALID_POSTID}) to make it work. 

But posts on the pages I manage it does not work on both. I get this error on either:

nsupported get request. Object with ID '{SOCIALID_POSTID}' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

or

(#12) singular statuses API is deprecated for versions v2.4 and higher

This only happens on the pages I manage
For videos and photos on the pages I manage, they work (There seems to be a difference on their urls for both videos and photos) , but on posts (e.g. just plain text posts) they don't.
Is there a work around on this?

Thanks.

**Comment by snarfed** [comment]
thanks for weighing in! yup, that's still the current state. you can get many posts by id, formatted one way or another, but not all, and it's not usually clear why either way. definitely keep us posted if you find any new info!

**Comment by nelson-temporal** [comment]
Ok. As I could see, all those posts with 'post' on their urls on pages I manage can't be accessed whatsoever using just POSTID or SOCIALID_POSTID (e.g. these seems to happen on text posts and shared videos and photos)
