### ISSUE TITLE
twitter: re-request publish permissions when logging into an existing publish account

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#518]
Not even showing up on https://www.brid.gy/twitter/singpolyma or https://www.brid.gy/facebook/515373050 -- I have made no changes on my side, was working last night.  (The ones you see there include a "preview" step because doing it manually still works).

**Comment by snarfed** [comment]
interesting! hmm. let's see. we changed publish to return 201 instead of 200 a month and change ago, #464, but i'm guessing that's not it, since they'd still show up on your user pages.

i see that we served your server (184.107.182.218, right?) a few 400s for facebook attempts recently since 1) we no longer support publishing FB likes and comments (sadly; https://www.brid.gy/about#facebook-publish) and 2) we don't support updating posts that have already been published. those also show up on your user page though.

i also see that we served you at least one 400 for twitter when publish wasn't enabled for your account.

otherwise, i'm not seeing any suspicious publish 4xxes, 5xxes, or crashes we would have served to you. do you have an example post URL that you tried to publish that isn't showing up on your user pages?

**Comment by singpolyma** [comment]
The most recent one that did go out from my twitter (which I did manually with a form) should have gone out on its own. Could be the wordpress webmention plugin failing, but it's worked up until now and I didn't change it...

I did notice that when I logged in to post with twitter it didn't show as enabled for publish... could that have expired or something?

**Comment by singpolyma** [comment]
I just hit the twitter button on the brid.gy homepage again and it shows me as not having publishing enabled again..

**Comment by snarfed** [comment]
ah, thanks. that's it. we don't handle permissions well when you have an existing account with publish enabled and you re-login from the front page. (this is because when you click the front page silo button, we don't know whether you have an existing account, or which one it is.)

for twitter, we currently disable publish. for facebook, i think it stays enabled, but the new access token doesn't have the FB permissions we need to actually publish. both are clearly bad UX.

the FB side is tracked in #482 and #481. i'll track the twitter side here. thanks for the nudge, and sorry for the trouble!

in the meantime, the workaround is probably just not to re-login from the front page, or if you do, re-enable publish too.

**Comment by snarfed** [comment]
note to myself: current proposed fix for both silos is to keep the current oauth flow, and when the silo redirects back to us, check whether this account already exists and has publish enabled, and if it does, do the flow *again* to request publish permissions.

still clearly not ideal, but i don't see a better way yet, apart from implementing full blown bridgy accounts so we know who you are when you log in on the front page. i'd definitely like to avoid that.

**Comment by snarfed** [comment]
hey @kylewm, any ideas on how to do better here than the straw man proposal above?

**Comment by kylewm** [comment]
I haven't thought of anything compelling. We could check that the preexisting token is still valid and just keep it if so, but that seems a little bit problematic with tokens like Facebook's that expire eventually ("why is it expiring when I just logged in yesterday?").

You could do the double-auth thing to solve the general case, and then improve that for users that have an account saved in the new cookie stuff -- just ask for more permissions up front if we know that user has an account with listen+publish.

**Comment by snarfed** [comment]
ooh i like it! i was thinking too black and white: "not everyone will have the login cookie, therefore we can't use it at all". using it for progressive enhancement is smart.

one catch is that the cookie may have multiple accounts for that silo. another is that they log into a different account on that silo. still, defaulting to the same perm level is probably ok; they can always disable publish afterward if they want.
