### ISSUE TITLE
Flickr not sending webmentions to Known

### ISSUE THREAD

**Issue by kevinmarks** [snarfed/bridgy#535]
https://brid.gy/flickr/35237099379@N01# says 'no webmention targets' for  https://www.flickr.com/photos/35237099379@N01/19508258254/ yet it links to http://known.kevinmarks.com/2015/homebrew-website-club-indiewebcamp-1

**Comment by kylewm** [comment]
We diagnosed this [on IRC](http://indiewebcamp.com/irc/2015-11-02#t1446500822871):
- The link in the photo caption is ignored because known.kevinmarks.com is not in Kevin's Flickr profile
- Posse-post-discovery doesn't find it because it's an older photo that's not on Kevin's h-feed anymore
- We could conceivably fetch the link to known.kevinmarks.com, looking for a u-syndication, and "upgrade" the post from a mention to a POSSE post if we find the syndication relationship

**Comment by snarfed** [comment]
thanks for diagnosing! the new domain req't is documented in https://brid.gy/about#domain .

fetching candidate links and looking for syndication URLs is an interesting idea, but also a substantial project. we can definitely consider it, but i probably wouldn't personally work on it any time soon. worth keeping in mind though.
