### ISSUE TITLE
facebook publish: support person-tags of non-Bridgy users

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#568]
If you Bridgy Publish to Facebook from a photo post with person-tags of FB profile URLs, the FB POSSE copy should be person-tagged with those FB profile URLs.

E.g. http://tantek.com/2015/341/t3/indiewebcamp-sf-building-future-web-mozilla

has 11 person-tags with FB profile URLs, yet the FB POSSE copy made with Bridgy Publish:

https://www.facebook.com/photo.php?fbid=10102006804080333

has only 8 person-tags.

Would appreciate if Bridgy Publish could copy-across all of the person-tags using profile URLs of the POSSE slio destination.

**Comment by snarfed** [comment]
:+1: thanks for filing!

we can currently only tag bridgy users because of #350 (can't look up users by username or global user id). we might be able to use the [taggable friends API](https://developers.facebook.com/docs/graph-api/reference/user/taggable_friends) ([more details](https://indiewebcamp.com/POSSE_to_Facebook#Mention_Tagging), bottom of section). it'd take a fair amount of work, and no guarantee they'd grant us the permission, but it's doable.

however, @kylewm raises the good point that it'd be difficult to match a mf2 person tag FB profile URL with its corresponding [UserTaggableFriend](https://developers.facebook.com/docs/graph-api/reference/user-taggable-friend/). the profile URL has just global id or username, while the UserTaggableFriend has full name and app scoped id. if the mf2 person tag text has the person's name, we might be able to use that. otherwise, this could be a showstopper. :(

**Comment by kylewm** [comment]
Here's a link to the FB docs for [Feature Review](https://developers.facebook.com/docs/apps/review/feature#reference-TAGGABLE_FRIENDS). The good news is we're not trying to do anything on the no-nos list.

Here's what one taggable friend looks like. (It's clearly intended for apps that want to give users a dropdown list of names/photos to select from)

```
{
  "data": [
    {
      "id": "AaJRHDGzPJqQK7jR2uUxZkh5ubtUIA3OPCj84t2WfR-eKhjpkUQPuib24ombGeIXw2B94lbLTftrdGHxR_PzjQ7UA9udTg7P_C4NtvMCYZcjrA",
      "name": "Joe Anybody",
      "picture": {
        "data": {
          "is_silhouette": false,
          "url": "https://scontent.xx.fbcdn.net/hprofile-xfa1/v/t1.0-1/c43.15.184.184/s50x50/384459_957949189983_1018386438_n.jpg?oh=099fd01023ede92de593f2395a6e9290&oe=5722516F"
        }
      }
    },
```

**Comment by snarfed** [comment]
thanks! oh man, also notable: that `id` is a taggable token, _not_ a user id (app-scoped or global).

**Comment by tantek** [comment]
So this just worked: http://tantek.com/2016/023/t2/indiewebcamp-nyc-day-2-independents Bridgy Publish POSSEd to https://www.facebook.com/photo.php?fbid=10102091548836163 
Facebook person-tagged a bunch of people who AFAIK have *never* signed up with Bridgy, and two of whom I'm not even friends with on FB, so that's a pretty neat trick.

Any idea how this magically worked so we can document it for others to repeat? (I did use numerical user IDs for everyone except myself). cc: @kylewm

**Comment by snarfed** [comment]
woo! sadly no, i don't understand the behavior, and [the docs don't say much](https://developers.facebook.com/docs/graph-api/reference/v2.2/user/photos#Creating). so far we've seen different combinations/suspicions of:
* numeric user ids vs usernames
* app-scoped vs global user ids
* users signed up for bridgy vs not
* friends of the poster vs not
* none of the above (e.g. https://github.com/snarfed/bridgy/issues/459#issuecomment-172917671)

whee!

**Comment by tantek** [comment]
I have near 100% reliability now when tagging people with facebook.com/number URLs. E.g. see this recent example (100% success) http://tantek.com/2016/154/t1/homebrew-website-club-mozilla-sf

**Comment by snarfed** [comment]
thanks! tentatively closing. documented the current state decently well in https://brid.gy/about#person-tag .
