### ISSUE TITLE
Bridgy Publish to Facebook: ensure each photo post shows up as its own post on timeline

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#571]
Ensure each photo post shows up as its own post on timeline instead of being clustered into an album post.

AKA: "prevent facebook from consolidating photo posts" 

"it'd be nice to be able to control that, but sadly i don't think it's possible right now" per https://developers.facebook.com/docs/graph-api/reference/v2.2/user/photos#Creating

but creating this issue just in case someone gets clever and figures out a way.

Related to #562

**Comment by snarfed** [comment]
thanks for filing! based on [this SO answer](http://stackoverflow.com/a/15362842/186123), it might actually doable if we upload photos to the special _Timeline Photos_ album, instead of just to `/me/photos` like we do now which defaults to the _Bridgy Photos_ album.

specifically, we'd fetch [`/me/albums`](https://developers.facebook.com/docs/graph-api/reference/user/albums), find the album with [`type="wall"`](https://developers.facebook.com/docs/graph-api/reference/v2.2/album/#readfields), and then upload the photo to [`/ALBUM_ID/photos`](https://developers.facebook.com/docs/graph-api/reference/album/photos#pubfields). worth a shot!

**Comment by kylewm** [comment]
> specifically, we'd fetch /me/albums, find the album with type="wall", and then upload the photo to /ALBUM_ID/photos. worth a shot!

Little heads up: when you upgrade to a newer API version, you'll have to request `?fields=type` explicitly

**Comment by snarfed** [comment]
true, thanks! annoying little gotcha. currently kinda tracked at https://github.com/snarfed/granary/blob/master/granary/facebook.py#L64 .
