### ISSUE TITLE
missing searched site link in tweet

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#595]
i thought bridgy does that already, catching twitter backlinks without http//: or https//:. this one at least wasn’t caught:
https://twitter.com/pheraph/status/686623020606197761

bridgy says, there’s no target in it:

<img width="1096" alt="bildschirmfoto 2016-01-12 um 09 28 51" src="https://cloud.githubusercontent.com/assets/4541494/12258427/03a61172-b90f-11e5-8f91-ad193230de26.png">

**Comment by snarfed** [comment]
thanks for the report! not sure what happened, i'll look. (the link itself is fine, twitter just renders links without the http/https, so that's not the problem.)

* tweet: https://twitter.com/pheraph/status/686623020606197761
* link: http://wirres.net/article/articleview/9043/1/6/
* Response entity: https://console.developers.google.com/datastore/entities/edit?project=brid-gy&kind=Response&queryType=gql&key=0%2F|8%2FResponse|44%2Fname:tag:twitter.com,2013:686623020606197761&gql=
* poll that found it: https://brid.gy/log?start_time=1452538949&key=aglzfmJyaWQtZ3lyEwsSB1R3aXR0ZXIiBmRpcGxpeAw

**Comment by snarfed** [comment]
relevant part of the [poll log](https://brid.gy/log?start_time=1452538949&key=aglzfmJyaWQtZ3lyEwsSB1R3aXR0ZXIiBmRpcGxpeAw):
```
"HEAD /9043 HTTP/1.1" 302 None
"HEAD /article/articleview/9043/1/6/ HTTP/1.1" 200 None
Resolved http://wirres.net/9043 to http://wirres.net/article/articleview/9043/1/6/
Original post discovery found original posts set([u'http://wirres.net/article/articleview/9043/1/6/']), mentions set([])
Demoting original post links because user tag:twitter.com,2013:diplix doesn't match author tag:twitter.com,2013:pheraph
Starting new HTTPS connection (1): twitter.com
"HEAD /pheraph/status/686623020606197761 HTTP/1.1" 200 None
```

**Comment by snarfed** [comment]
i've been investigating this a fair amount, but haven't figured it out yet. normally i'd guess is that it was found by both the user mention search - _@diplix_ - and the site link search - _http://wirres.net/9043_ - and they collided, but if that happened and there was a bug, at least one of the two would still come through. so i'm stumped.

**Comment by snarfed** [comment]
tentatively closing. apologies @diplix, i never figured this one out, but i also haven't heard reports of other missing link tweets like this. feel free to reopen if you know of any more recent examples!
