### ISSUE TITLE
create UI to return bridgy URL given a silo post URL

### ISSUE THREAD

**Issue by aaronpk** [snarfed/bridgy#617]
I would love to see a form that takes a supported silo URL (e.g. https://twitter.com/luxagraf/status/699605447414804480) and turns it into the bridgy URL (e.g. https://brid.gy/post/twitter/aaronpk/699605447414804480) 

This would make it easier for me to create the bridgy URLs to manually send myself webmentions for old posts that didn't get linked up with Bridgy.

**Comment by snarfed** [comment]
[discussed on IRC.](http://indiewebcamp.com/irc/2016-02-16#t1455640941859) would take a bit more work because it needs more inputs, eg whether a tweet is being interpreted as a normal tweet or reply or RT, or the liking/reposting user for likes/reposts.

more importantly, #579 would probably subsume this and might be more worthwhile.

**Comment by aaronpk** [comment]
Agreed. Happy to retract this suggestion :)
