### ISSUE TITLE
Syndicated photo to FB not polled/crawled

### ISSUE THREAD

**Issue by danito** [snarfed/bridgy#637]
https://nxd4n.nixekinder.be/2016/le-direct-en-direct 
   -> https://facebook.com/10208087975974630 
       -> https://www.facebook.com/photo.php?fbid=10208087975974630&set=a.10206162015306817.1073741828.1156781735&type=3&theater
but it doesn't show up on https://brid.gy/facebook/1156781735#
Any idea?

**Comment by snarfed** [comment]
sigh, blame facebook. they sometimes don't give us enough information to determine whether a photo is public: https://brid.gy/about#enough+information . sometimes it's actually unclear from looking at the UI too. this is one of those cases.

specifically, the post is one of those auto-consolidated "Daniel Nix added N new photos." posts: https://www.facebook.com/photo.php?fbid=10208083660306741&set=p.10208083660306741&type=3 . the API object has this:

```json
  "privacy": {
    "allow": "",
    "deny": "",
    "description": "",
    "friends": "",
    "value": "CUSTOM"
  },
```

which we can't infer anything about, public or private or otherwise.

the photo object itself doesn't have a `privacy` field, and the album, https://www.facebook.com/album.php?fbid=10206162015306817&id=1156781735&aid=1073741828 , has `"privacy": "friends"`.

in the future, you can probably avoid this problem by making that album public, or by posting photos to another album that is public. (you can also avoid the auto-consolidated posts by posting to the Timeline Photos album.)
