### ISSUE TITLE
Disable Tumblr button fails

### ISSUE THREAD

**Issue by billbennettnz** [snarfed/bridgy#638]
Hit the disable Tumblr button.

Get a Tumblr dialog asking if it's OK to give Bridgy access. 

Clicking 'No way' gets me to a 400 bad request page. https://brid.gy/delete/finish?declined=True

I can (and have) delete the app permission from Tumblr settings. 

Bridgy is still looking for Tumblr webmentions.

**Comment by kylewm** [comment]
> Get a Tumblr dialog asking if it's OK to give Bridgy access.

Yeah, this is a really awkward interaction -- You need to click "OK" instead of "No way". In order to disable your account, Bridgy has to know you are the owner of the Tumblr page, so it asks for you to identify yourself via Tumblr. If you click "OK" when Tumblr asks you to give Bridgy permission, then Bridgy will properly remove/disable your account. (You can then go in and delete the app from Tumblr settings)

Unfortunately Tumblr doesn't support "authenticate" (identify yourself without granting permission) like the other services that Bridgy supports, so it always asks for access when really it just needs identity.

**Comment by billbennettnz** [comment]
Thanks. Yes that works. 

I disabled Tumblr because it was generating tons of "No microformats2 data found" webmention errors, but I don't really use Tumblr except as a way of backing up my Wordpress.com site. 

Is there a way to get the Tumblr link off my Bridgy home page? I realise this may look fussy, but it's  something mainstream users will expect when they turn up.

**Comment by kylewm** [comment]
I'll defer to @snarfed on that question
 
 
On Sat, Mar 26, 2016, at 04:19 PM, Bill Bennett wrote:
> Thanks. Yes that works.
> I disabled Tumblr because it was generating tons of "No microformats2
> data found" webmention errors, but I don't really use Tumblr except as
> a way of backing up my Wordpress.com site.
> Is there a way to get the Tumblr link off my Bridgy home page? I
> realise this may look fussy, but it's  something mainstream users will
> expect when they turn up.
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/snarfed/bridgy/issues/638#issuecomment-201949268

**Comment by snarfed** [comment]
thanks for the triage @kylewm, and sorry for the trouble @billbennettnz! we should definitely make this less confusing. we can tell you when you hit "disable" that you'll need to approve the prompt, and we can definitely improve the error message when you decline. i'll do that.

> Is there a way to get the Tumblr link off my Bridgy home page?

not sure what you mean. which link, on which home page?

**Comment by kylewm** [comment]
I think it's the one at the top right (the little shortcut that gets created and stored in a cookie)

**Comment by billbennettnz** [comment]
Yes, that's the one. I managed to kill it when I set up a new identity (to stop all the comments on my website being posted my name).

**Comment by snarfed** [comment]
ah, thanks.
