### ISSUE TITLE
Reply to twitter mobile url not working?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#643]
https://mobile.twitter.com/singpolyma/status/717043160803708928 doesn't seem to be set up as a reply properly

**Comment by snarfed** [comment]
true! thanks for filing.

**Comment by snarfed** [comment]
i looked into this, and bridgy actually supports mobile.twitter.com ok. the problem is that [your post](https://singpolyma.net/actionstream/reply-httpsmobile-twitter-comgrt_rowstatuses717040792179703808-grt_row/) uses `rel="in-reply-to"`, while bridgy only supports `class="u-in-reply-to"`.

i'm not sure how widely supported rel-values ever were in mf2, but at best [it seems like they're deprecated now](https://indiewebcamp.com/rel-values#Brainstorming_rel_vs_class). i think part of that is that they're page scoped, not element scoped, so they break in feeds with multiple items breaks.

**Comment by singpolyma** [comment]
I don't think my markup has changed... but I guess I can add another mf2 class. I have a couple of them already for likes and such

**Comment by snarfed** [comment]
discussion: http://indiewebcamp.com/irc/2016-04-04#t1459818479344

**Comment by snarfed** [comment]
@singpolyma looking at bridgy's stored html for your past published @-replies, you actually used to have `class="u-in-reply-to"`. maybe you unintentionally dropped it recently?

**Comment by singpolyma** [comment]
I must have done something wrong in my recent server migration. Sorry about that! I'll fix my markup :)
