### ISSUE TITLE
facebook person-tags not working

### ISSUE THREAD

**Issue by j4y-funabashi** [snarfed/bridgy#674]
I POSSEd this post http://j4y.co/p/20160621175531_576971837c187 which has my facebook profile url as a person-tag and it did not get pushed to facebook

**Comment by j4y-funabashi** [comment]
please let me know if you need anymore details

**Comment by snarfed** [comment]
this is great, thanks!

profile: https://brid.gy/facebook/j4y.co

**Comment by snarfed** [comment]
so i think i misspoke in irc. it looks like we only support links to FB user ids right now, not usernames or web sites. details on how to find someone's FB user id: https://indiewebcamp.com/person-tag#Bridgy_Publish

this may have been a regression. I'll try to add back support for those kinds of links. not sure it will work, since i suspect FB needs global user ids for tags, not app scoped, but I'll keep this open to track!

**Comment by snarfed** [comment]
background: #318, #459, #568

**Comment by snarfed** [comment]
aha, i was wrong, we do domains and FB usernames in person tag links after all.

AS object snippet from this post ([log](https://brid.gy/log?start_time=1466529887&key=aglzfmJyaWQtZ3lyUwsSDVB1Ymxpc2hlZFBhZ2UiLGh0dHA6Ly9qNHkuY28vcC8yMDE2MDYyMTE4MjIzOF81NzY5NzdkZTY2N2JmDAsSB1B1Ymxpc2gYgICAgICAgAkM)):

```json
"tags": [{
  "url": "https://www.facebook.com/alexandra.pinnock.35",
  "displayName": "@https://www.facebook.com/alexandra.pinnock.35",
  "objectType": "person"
  }, 
  "..."
}]
```

still investigating.

**Comment by snarfed** [comment]
so, `https://www.facebook.com/alexandra.pinnock.35` didn't work because she's not signed up for bridgy, so we don't know her username => user id mapping, and `https://www.facebook.com/jay.funabashi00xx.940436` didn't work because we don't know your username either (and haven't seen a syndication URL to infer it from yet). background on FB usernames and user ids. background in #568, #350, etc.

...yeah, person tagging is obviously limited. :P i'll add all this to the docs.
