### ISSUE TITLE
Multiple Brid.gy URL:s pinged for same tweet

### ISSUE THREAD

**Issue by voxpelli** [snarfed/bridgy#683]
When debugging a duplicate post issue in my endpoint (https://github.com/voxpelli/webpage-webmentions/issues/35) I found that multiple different Brid.gy URL:s had been pinged to my endpoint for the same tweet and thus that I had imported the tweet multiple times as I only do deduplication on a normalized source URL, not on the actual content of the Microformats 2 data itself.

I searched the issues and PR here and found no mentioning of any issues around it so opening a new one.

These pings was received for http://www.kevinmarks.com/decentralweb2016-06-08.html at 2016-06-12 03.26 (unsure what timezone, but I guess UTC).

The first three URL:s pinged was:

* https://brid-gy.appspot.com/post/twitter/kevinmarks/741827388313456640
* https://brid-gy.appspot.com/post/twitter/kevinmarks/741826520285470720
* https://brid-gy.appspot.com/post/twitter/kevinmarks/741826676758216705

**Comment by snarfed** [comment]
interesting. thanks for filing!

looks like [741826520285470720](https://twitter.com/internetarchive/status/741826520285470720) is the original tweet that quotes [this @kevinmarks tweet](https://twitter.com/kevinmarks/status/741757452924813314), and [741827388313456640](https://twitter.com/_/status/741827388313456640) and [741826676758216705](https://twitter.com/_/status/741826676758216705) are RTs of it. example RT tweet object from the API:

```json
"id_str": "741827388313456640",
"retweeted_status": {
  "created_at": "Sun Jun 12 02:56:39 +0000 2016",
  "id": 741826520285470700,
  "id_str": "741826520285470720",
  "text": "A great guide to the full videos https://t.co/DhQoGDv3MT #DWebSummit. We want u to share, reuse open knowledge. https://t.co/cddL6GC8Nr",
  "..."
}
```

we try to avoid backfeeding RTs of quote and link tweets, but this might be a bug in that. i'll investigate.

...having said that, i'd encourage you to de-dupe on `u-url` instead of normalized source URL. i saw your discussion in https://github.com/voxpelli/webpage-webmentions/issues/35#issuecomment-232399605 , and know it'd probably be a big switch, but it's arguably the right thing to do. it looks like https://indieweb.org/Webmention-brainstorming#de-duplication agrees.

re:
> that would in a way be a Brid.gy specific fix as such a dedupe would enable a third party to block a true Webmention by being the first to ping with a specific u-url, no matter of it owns that url or not.

you'd still want to accept updates, so the third party wm wouldn't necessarily "block" future wms with the same `u-url`, but it definitely could spoof or overwrite them afterward. from https://indieweb.org/Webmention-brainstorming#de-duplication :
>  security / identification / preventing hijacking. An attacker could overwrite or delete an existing webmention by sending a new one from their own site with the same u-url. To prevent this, receivers can compare source domain as well as uid, u-url, etc., and only interpret two webmentions as duplicates if both match.

cc @kevinmarks
