### ISSUE TITLE
facebook: consistent 500 on GET /me/feed for one account

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#689]
...specifically @barnabywalters, https://brid.gy/facebook/100001398384863 . [example log](https://brid.gy/log?start_time=1469314629&key=aglzfmJyaWQtZ3lyIQsSDEZhY2Vib29rUGFnZSIPMTAwMDAxMzk4Mzg0ODYzDA):

```
Updating Barnaby Walters (Facebook) /facebook/100001398384863 : {'poll_status': 'polling', 'last_poll_attempt': datetime.datetime(2016, 7, 23, 22, 57, 9, 201310)}
urlopen GET https://graph.facebook.com/v2.6/me/feed?offset=0&fields=id,application,caption,comments,created_time,description,from,likes,link,message,message_tags,name,object_id,parent_id,picture,place,privacy,reactions,sharedposts,shares,source,status_type,story,to,type,updated_time,with_tags&limit=50&access_token=... {}
Error 500, response body: {"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"HWcCffZuLtB"}}
API call failed. Marking as error and finishing.
```

**Comment by snarfed** [comment]
posted on a facebook api bug: https://developers.facebook.com/bugs/620828738095197/?comment_id=1790552947844955

**Comment by snarfed** [comment]
[facebook replied:](https://developers.facebook.com/bugs/620828738095197/?comment_id=1058658744170910)

> I can confirm this is the same issue as the original bug reporter but at this time the team handling this haven't identified the exact cause or a fix - it appears to be caused by some specific post or post's on that user's /feed connection, so you may be able to work around this with smaller limits and/or using the older limit/offset pagination to 'skip' the offending post
>
> Unfortunately I can't see which specific posts are causing it in this case, though

**Comment by barnabywalters** [comment]
Ah yeah I noticed that! I haven’t posted very much recently so we might be able to track down what it was easily enough.

The last post which I successfully received facebook bridgy backfeed for was this one: https://waterpigs.co.uk/notes/4htH3a/

Since then I have posted:

https://waterpigs.co.uk/notes/4hx8Et/ <- received no reactions anywhere
https://waterpigs.co.uk/notes/4hxCKw/ <- first post to not receive facebook backfeed
https://waterpigs.co.uk/notes/4hxCMi/ <- v Future posts also affected, but posted after observing the bug
https://waterpigs.co.uk/notes/4i3FX9/
https://waterpigs.co.uk/notes/4iDKxe/
https://waterpigs.co.uk/notes/4iF7Vp/
https://waterpigs.co.uk/notes/4iFDnE/
https://waterpigs.co.uk/notes/4iS6sH/

Any ideas? I’m stumped, but have little experience with the relevant facebook API.

**Comment by barnabywalters** [comment]
It feels strangely good to know that something I posted broke facebook ;)

**Comment by barnabywalters** [comment]
@snarfed any ideas about what could be done about this? I’m missing having facebook reactions backfed to my site, although I appreciate that this is probably a low-priority bug as it only seems to affect me.

I just used the facebook dev tools to generate an access token and ran the query given in the bridgy logs myself, which worked absolutely fine:

<img width="929" alt="screen shot 2016-08-08 at 17 20 38" src="https://cloud.githubusercontent.com/assets/968350/17485016/ac6b6b14-5d8c-11e6-80dd-f98ce8743df1.png">

…so I thought re-signing in to bridgy might fix the problem, but apparently not. It looks like the problem might be with bridgy rather than the query itself or the facebook API? Can you somehow reset my account or clear the access token?

**Comment by snarfed** [comment]
:( sorry for the trouble @barnabywalters. i'd definitely miss FB backfeed if i'd been without it for a month too!

the access token you generated probably doesn't have the same permissions as bridgy's, and facebook fetches and returns some data based on token permissions, so that might be the difference. you also did the right thing by re-signing into bridgy, since that generates and stores a new token.

i reread FB's response and tried special casing your account to just fetch fewer posts, and it looks like that worked. (yay!) it may also show us which post of yours is the problematic one, like FB described. more to come.

**Comment by barnabywalters** [comment]
oh super, thanks! Let me know if I can help further. The only permission I checked for the dev access token was access to posts, I can try again with other permissions if that’d be useful.

**Comment by barnabywalters** [comment]
Hundreds of notifications suggests backfeed is working again now — thanks!

Interestingly, nothing happened for these two posts:

https://waterpigs.co.uk/notes/4iF7Vp/ https://www.facebook.com/photo.php?fbid=1122285747828027&set=a.149404371782841.28962.100001398384863&type=3&theater
https://waterpigs.co.uk/notes/4ifL1N/ https://www.facebook.com/photo.php?fbid=1139168566139745&set=a.149404371782841.28962.100001398384863&type=3&theater

But if everything else is working again now then I’m not too worried. Thanks for sorting this out!

**Comment by snarfed** [comment]
[updated the facebook bug](https://developers.facebook.com/bugs/620828738095197/?comment_id=1063921620357451):

> i debugged a bit more, and i think i've narrowed down the exact post(s) that are breaking:
> https://www.facebook.com/photo.php?fbid=872136706231010&set=a.417900731654612.1073741829.100003040678433&type=3
> https://www.facebook.com/photo.php?fbid=872681772843170&set=a.417900731654612.1073741829.100003040678433&type=3
> 
> (they go together; one is a post with a photo, and one is the automic cluster of a set of photos.)
> 
> the API calls that found this:
> 
> `me/feed?offset=0&limit=36&fields=...`  (ok)
> `me/feed?offset=38&fields=...`  (ok)
> `me/feed?offset=37&limit=1&fields=...`  (returns the above error)

**Comment by snarfed** [comment]
happening to a couple other accounts now too. both started ~6d ago.

https://brid.gy/facebook/121871574551570
https://brid.gy/facebook/559255850862175

**Comment by snarfed** [comment]
woo, [sounds like they found the bug, and they'll push a fix soon](https://developers.facebook.com/bugs/620828738095197/?comment_id=1405782436104441).

**Comment by snarfed** [comment]
[evidently that fix wasn't for this bug.](https://developers.facebook.com/bugs/620828738095197/?comment_id=339139196418645) :/

**Comment by snarfed** [comment]
the bad post is past the first 50 items now, so i've dropped the special case.

**Comment by snarfed** [comment]
happening again, this time to @jonnybarnes. http://brid.gy/facebook/10207093222641618

```
I urlopen GET https://graph.facebook.com/v2.6/me/feed?offset=0&fields=id,application,caption,comments,created_time,description,from,likes,link,message,message_tags,name,object_id,parent_id,picture,place,privacy,reactions,sharedposts,shares,source,status_type,story,to,type,updated_time,with_tags&limit=50&access_token=... {}
W Error 500, response body: {"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":..."fbtrace_id":"BKiV2vLyESG"}}
E API call failed. Marking as error and finishing. 500: {"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":..."fbtrace_id":"BKiV2vLyESG"}}
```

**Comment by snarfed** [comment]
i've filed a new facebook bug: https://developers.facebook.com/bugs/1800000083618507/

i'll also add a special case in bridgy to handle this temporarily.

**Comment by snarfed** [comment]
woo FB finally fixed the bug on their end!

> The issue relates to a small number of posts whose privacy values are corrupted, but should be resolved after we roll out an update.

**Comment by jonnybarnes** [comment]
Can we close this issue now then?

**Comment by snarfed** [comment]
yup, thanks, done.
