### ISSUE TITLE
404 on reacji from facebook log entries

### ISSUE THREAD

**Issue by petermolnar** [snarfed/bridgy#698]
This is a reacji, which I received safe and sound:
https://brid.gy/log?start_time=1471082827&key=aglzfmJyaWQtZ3lyTwsSCFJlc3BvbnNlIkF0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxNTM4NTcyOTYwMjEyMzVfbG92ZV9ieV8xMDE1Mzc4MDYxNjI5NDcwNww

However, the bridgy URL in there ( https://brid-gy.appspot.com/react/facebook/584261234/10153857296021235/10153780616294707/10153857296021235_love_by_10153780616294707 ) gives me a 404 at the moment.

**Comment by snarfed** [comment]
ugh. this happens with facebook sometimes, and we don't always know why. :( background in #512.

in this case, it's probably because of facebook's photo clustering. these photos show up individually in your feed, and this reaction is on an individual photo, but when we use the FB API to fetch the photo by id, we get the cluster instead:

https://www.facebook.com/584261234/posts/10153857296021235

we've put a lot of work into handling this clustering, for both backfeed and publish - #562 #571 #611 #661 - but it's still definitely not perfect, and may never be. :/

**Comment by snarfed** [comment]
tentatively closing to fold tracking into #512. feel free to reopen!
