### ISSUE TITLE
Duplicate @reply prepended to tweet

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#703]
https://brid.gy/log?start_time=1476791704&key=aglzfmJyaWQtZ3lymQELEg1QdWJsaXNoZWRQYWdlInJodHRwczovL3Npbmdwb2x5bWEubmV0L2FjdGlvbnN0cmVhbS9yZXBseS1odHRwc3R3aXR0ZXItY29tamxhbW90aGUxOTgwc3RhdHVzZXM3ODgyMDM2NDk2NDYzOTk0ODgtamxhbW90aGUxOTgwLXlvdS8MCxIHUHVibGlzaBiAgICAgICACgw

**Comment by snarfed** [comment]
oops! thanks for the report this is probably due to recent changes we made for twitter's new "extended tweet" char counting changes, snarfed/granary#89:
https://brid.gy/about#extended-tweets
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

...yup, that tweet's API object shows that twitter itself added the first @-mention because bridgy uses the new `auto_populate_reply_metadata=true`. the `display_text_range` puts it outside of the text that should be displayed.

```json
{
  "id_str": "788347659916484608",
  "full_text": "@jlamothe1980 @jlamothe1980 you want lift from https://t.co/i70VL80zbH (https://t.co/ahUg4B5gS7)",
  "display_text_range": [
    14,
    96
  ],
  "..."
```

i think the conclusion is that twitter's UI(s) themselves haven't quite caught up to their own changes yet. i expect they will soon. in the meantime, i'd suggest that you now omit the in-reply-to @-mention in your replies. (sorry, i know bridgy/twitter used to require it!)

i'll figure out a way to PSA this to bridgy publish users.

**Comment by singpolyma** [comment]
could bridgy remove if present before sending to twitter?

**Comment by snarfed** [comment]
definitely a good idea. doing that the Right Way would mean i'd need to fetch the in-reply-to tweet, but i could probably hack it by just parsing the username out of the URL, which should work almost all the time. i'll do that.
