### ISSUE TITLE
Bridgy stopped finding my webmention endpoint

### ISSUE THREAD

**Issue by klischka** [snarfed/bridgy#713]
Since one week bridgy does not recognize anymore http://stromgeber.lischka.cc/ as an endpoint for many favs, retweets, replies and the like I get on  http://twitter.com/klischka for content syndicated from there (a withknown installation): 

I did not change anything in the profile on twitter or on the known-site. 

When polling, the URL is not recognized anymore. Part of polling log:
2016-12-27 15:04:51.619170 I requests.get http://www.konradlischka.info/ {'headers': {'Accept': '...', 'User-Agent': '...'}}
2016-12-27 15:04:54.330369 D No h-feed found, fallback to top-level h-entrys.
2016-12-27 15:04:55.034180 D fetching author url http://lischka.pics/
2016-12-27 15:04:55.034830 I requests.get http://lischka.pics/ {'headers': {'Accept': '...', 'User-Agent': '...'}}

Any ideas on this? Thanks!

**Comment by snarfed** [comment]
hi @klischka! sorry for the trouble. looks like this was a bad side effect of the fix for #711, which added [content negotiation](https://en.wikipedia.org/wiki/Content_negotiation) via the HTTP `Accept` request header. thanks for reporting!

cc @rhiaro @benwerd. the change added the `Accept: text/html; q=0.1, application/json; q=0.9, */*; q=0.8` header to bridgy's outgoing HTTP requests. this convinced @rhiaro's web site to serve HTML, but oddly makes Known serve JSON instead. if i cut it down to just `Accept: text/html`, Known serves HTML. i thought maybe Known wasn't handling the `q=` priority flags, but it still serves JSON even if i drop them.

@rhiaro, could you advise? am i missing some con-neg best practice(s) for ensuring compatibility across servers?

**Comment by rhiaro** [comment]
I think your `q` values are inverted. You should set `q=0.9` to prioritise HTML, `0.1` is lowest priority, so it's overridden by the request for JSON.

I think my server ignores `q` values because I'm lazy, but Known is behaving correctly. 

Best practice though would be not to ask for JSON at all if you can't use it, just ask for HTML.

**Comment by rhiaro** [comment]
I think your `q` values are inverted. You should set `q=0.9` to prioritise HTML, `0.1` is lowest priority, so it's overridden by the request for JSON.

I think my server ignores `q` values because I'm lazy, but Known is behaving correctly. 

Best practice though would be not to ask for JSON at all if you can't use it, just ask for HTML.

**Comment by snarfed** [comment]
argh sorry, bad copy/paste. that was from one of my debugging experiments. [bridgy is actually sending](https://github.com/snarfed/bridgy/blob/a937592738548f7064918e84a0dc1eae4fbb8999/util.py#L49) `Accept: text/html, application/json; q=0.9, */*; q=0.8`.

you're right about only asking for HTML though. bridgy definitely wants and uses JSON in many cases, just not this one, but right now it's easier for me to use the same header in all requests. that's an implementation detail. i can try to differentiate in the future.

**Comment by snarfed** [comment]
i tried other explicit `q`s for `text/html` too, but no luck:
* `Accept: text/html; q=1.0, application/json; q=0.9, */*; q=0.8`
* `Accept: text/html; q=0.99, application/json; q=0.9, */*; q=0.8`

in case it matters, @klischka's server says it is `Server: Apache/2.2.15 (CentOS)`.

**Comment by rhiaro** [comment]
Hm, in that case I don't know. I was just suggesting to use explicit `q=1` for HTML when your other message came through. Maybe Known ignores `q` and prioritises JSON if it appears anywhere in the Accept. Need a Known representative to confirm or deny..

**Comment by klischka** [comment]
Thank you for getting back to this. It is Known Version: 0.9.2

**Comment by snarfed** [comment]
this has evidently broken backfeed entirely for Known users. :/ as a temporary workaround, i'm going to to limit sending the `Accept` header to just rhiaro.co.uk for now.

**Comment by rhiaro** [comment]
Thanks for the special exception snarfed! Sorry for the fuss :s

**Comment by snarfed** [comment]
done. @klischka, if you add http://stromgeber.lischka.cc/ back to your twitter profile and re-sign up for bridgy, you should hopefully get backfeed again.

**Comment by klischka** [comment]
Works perfectly - thank you!

**Comment by drikkes** [comment]
Hey,
I had the same problem, but after re-connecting everything's fine with Twitter again.
But now it seems my Facebook syndication broke?  I get "No webmention targets" for my Known, but with Wordpress it's still working...

**Comment by snarfed** [comment]
@drikkes glad twitter is working again! and sorry facebook is broken. thanks for reporting.

looking at http://drikk.es/ , the only post i see in the last few weeks with a syndication link to facebook is http://drikk.es/2017/musste-es-im-logan-trailer-denn-unbedingt-johnny-cashs-hurt-cover-sein , which does have likes and comments on facebook. your bridgy user page https://brid.gy/facebook/10206219375153745 shows that it found those responses, and the logs show that it found the syndication link, so i'm not sure what's up. i'll keep looking.

**Comment by drikkes** [comment]
Jep, that's it. Thanks for investigating.

**Comment by snarfed** [comment]
looks like we are sending Facebook webmentions to drikk.es now: http://drikk.es/2017/die-dinger-vermehren-sich#comments

i suspect the day or two we missed was due to caching the missing Known endpoint due to idno/Known#1622. sorry @drikkes! if you want, you can fill in those responses manually with https://brid.gy/about#source-urls .
