### ISSUE TITLE
Error with URL shortener domain

### ISSUE THREAD

**Issue by davidmead** [snarfed/bridgy#729]
I've been posting fine, using Bridgy Publish on Wordpress, to Twitter with a URL shortener. I tried posting something just now and got the following error.

<img width="819" alt="bridgy_error_in_wordpress" src="https://cloud.githubusercontent.com/assets/1266930/23108826/eace2c14-f6e0-11e6-82ad-f75f9d5f53ac.png">

> Bridgy Error: Could not find <b>Twitter</b> account for <b>djm.click</b>. Check that your Twitter profile has djm.click in its <em>web site</em> or <em>link</em> field, then try signing up again.

The post content was...

```
I'm very happy to hear that. PS - Stickers arrived. Thank you :-)
[caption id="attachment_13152" align="alignright" width="3286"]<img src="http://davidjohnmead.com/blog/wp-content/uploads/2017/02/img_20170219_200329.jpg" alt="stickers on my Macbook Pro" width="3286" height="2432" class="u-photo size-full wp-image-13152" /> Technorati sticker from @mholzschlag[/caption]
<p>in reply to:
<a href="https://twitter.com/mholzschlag/status/833211562881998848" class="u-in-reply-to">[embed]https://twitter.com/mholzschlag/status/833211562881998848[/embed]</a></p>
```

[Posted to my blog](http://davidjohnmead.com/blog/2017/02/19/13151/) just fine, but didn't show up on Twitter.

Five hours ago [I posted](http://davidjohnmead.com/blog/2017/02/19/13149/) and did **not** get an error. It [syndicated fine to Twitter](https://twitter.com/davidmead/status/833414893235736577), using the short URL.

![image](https://cloud.githubusercontent.com/assets/1266930/23108939/16d4eb26-f6e2-11e6-85bd-f328392e72db.png)

No updates to WP or plugins happened in the meantime.

Any ideas?

**Comment by snarfed** [comment]
ruh roh. sorry for the trouble!

looks like this is because your site is unhappy. when i load http://djm.click/blog/b/3eB right now, i get a 500 with:

_This website is under heavy load_

_We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later._

your site asked bridgy to publish that post three times: 17:07, 17:37, and 17:39 PST. the first time, when bridgy tried to fetch the source URL, your site 500ed. the second time, your site closed the connection. the third time, bridgy didn't bother fetching since it was too soon since the last failure.

**Comment by davidmead** [comment]
Hmm. That's really odd. I just clicked on that link and it opened to http://davidjohnmead.com/blog/2017/02/19/13151/ (in an incognito tab) straight away.

Cant think why my site would be overloaded (I'm no web guru).

Let me try posting something new.

**Comment by davidmead** [comment]
Thanks for looking into it @snarfed. [Posted a test](https://twitter.com/davidmead/status/833513895960670211), and it worked fine. 

Wonder what on earth was causing it 500 like that?

**Comment by snarfed** [comment]
tentatively closing.
