### ISSUE TITLE
Bridgy web UI shows author instead of invitee for invitation backfeeds

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#754]
Bridgy's web UI for displaying "invitation" backfeeds may have broken at some point - I'm seeing all invitations just say *I* (event organizer) was invited (like 20 of them) instead of the actual person that was invited.
e.g. https://brid.gy/facebook/214611?responses_before=2017-07-03T16:51:21#responses
lots of "Tantek Çelik is invited." when I did no such thing - I did invite ~40 people though

However the actual Bridgy backfeed synthetic invitation responses appear to have correct mf2, e.g. https://pin13.net/mf2/?url=https%3A%2F%2Fbrid-gy.appspot.com%2Frsvp%2Ffacebook%2F214611%2F1935019616733708%2F10207297163250970

Thus it looks like a Bridgy web UI bug, not a backfeed bug.

**Comment by snarfed** [comment]
ruh roh! thanks for the detailed sleuthing, and sorry for the trouble. I'll look soon.

**Comment by snarfed** [comment]
fixed! visible on https://brid.gy/facebook/214611?responses_before=2017-07-03T16:52:01.052890#responses . thanks again for reporting, @tantek!

**Comment by chrisaldrich** [comment]
I'm getting something akin to this on WordPress, though the appearance within Bridgy appears as one would expect.
example: https://brid.gy/facebook/5410052?responses_after=2017-11-30T21:07:47#responses

Yet within WordPress, in the database all the invitees (via Facebook) appear with my name and facebook avatar instead of what I'd expect to be the invitee's name and avatar.

The data I'm seeing within comment meta for an example "invitation" (https://brid-gy.appspot.com/rsvp/facebook/5410052/169650146961455/318643335139472) is as follows
semantic_linkbacks_type: reply
semantic_linkbacks_author_url: https://www.facebook.com/5410052 (my FB ID)
semantic_linkbacks_avatar: https://graph.facebook.com/v2.10/5410052/picture?type=large (my FB avatar)

I would expect it to be:
semantic_linkbacks_type: rsvp:invited
semantic_linkbacks_author_url: https://www.facebook.com/318643335139472 (invitee ID)
semantic_linkbacks_avatar: https://graph.facebook.com/v2.10/318643335139472/picture?type=large (the invitee avatar)

Since the data within Brid.gy looks as expected, is it then the Webmention plugin that's not picking up/translating the data properly? 

Another thing I notice is that if I "massage" the data in the database to what I expect (as noted above), there are two entries that show up on the page for the invitees: one as an avatar in the facepile in the invitee section for RSVPs, and a separate one which appears as a generic webmention that indicates "invited". (Perhaps this is because it's not expecting a value of "invited"?)
Example: http://boffosocko.com/2017/11/30/virtual-homebrew-website-club-meetup-on-december-13-2017/#Jervey (see Jervey or Rachel as examples for which I've changed the metadata to what I would expect to be correct.)
 
As an example of an invitation (via Facebook) that's displayed without modification see: http://boffosocko.com/2017/11/30/virtual-homebrew-website-club-meetup-on-december-13-2017/#1:07+pm which corresponds with https://brid-gy.appspot.com/rsvp/facebook/5410052/169650146961455/318643335139472

@snarfed, you may be best suited to know given your recent work with the facepiles and knowledge of webmentions, but let me know and I'm happy to crosspost this to semantic linkbacks and/or webmentions if it's more germane in one of those.

Have you or anyone else used WordPress for Events with POSSE to Facebook before? I'd seen similar Facebook backfeed results to this within WithKnown in the past on July 3 and before (eg: http://stream.boffosocko.com/2017/virtual-homebrew-website-club-meetup-july-8-2017), but I haven't used it since you pushed the change on July 7, so I'm not sure how Known behaves now.)

**Comment by snarfed** [comment]
interesting! thanks for reporting. looks like this is a semantic-linkbacks bug, i'll file it there.
