### ISSUE TITLE
Replying to a user's homepage creates a tweet to one of their recent tweets?

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/bridgy#760]
I created a reply (https://eddiehinkle.com/2017/07/19/5/reply/) to a user's homepage (https://grant.codes/) that contains a rel=me for Twitter. When I used bridge publish for Twitter, I expected that my tweet would become a targeted tweet to @grantcodes (The twitter user that has the rel=me from grant.codes. 

Instead it become a reply to the user's most recent tweet: https://twitter.com/EddieHinkle/status/887677729113550848

Expected behavior: My reply to https://grant.codes should become a tweet with @grantcodes but not in reply to any specific tweet.

**Comment by snarfed** [comment]
heh. one key point here is that you actually replied to his home page, ie `<a class="u-in-reply-to" href="http://grant.codes/">, which is unusual and rarely used in indieweb, if ever. not sure what it would mean. :P you probably just wanted to mention it instead, ie without the `class="u-in-reply-to"`., not actually reply to it. homepage mentions, not replies, are the equivalent to twitter @-mentions.

what bridgy did was, the in-reply-to wasn't to twitter, so it tried to be smart and looked for a syndication link to twitter on that page...which there were plenty of, since `rel=syndication` is page scoped. :( so it used the first one. sigh. damn rel page scoping.

i guess one fix is to just disable that behavior for home pages specifically.

**Comment by snarfed** [comment]
thanks again for reporting @EdwardHinkle!
