### ISSUE TITLE
Mentioning an indieweb homepage doesn't create an @mention on Twitter

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/bridgy#761]
Current Behavior: I created a post that mentions a user's homepage (https://eddiehinkle.com/2017/07/19/9/note/). I sent a webmention to bridgy to tweet the note. It tweeted a note with the next in the note, rather than @mentioning the user (https://twitter.com/EddieHinkle/status/887766002246856704).

Expected Behavior: I create a post that mentions a user's homepage, I webmention to bridge to tweet it and it sends a tweet with the content of my note and an @mention of the user's twitter.

**Comment by snarfed** [comment]
yup, i figured this would be the next request. :P the key question here is, how does bridgy find the twitter username for a web site?

it may know it if that web site is signed up for bridgy, but many (most) aren't. it's also possible that the web site has more than one twitter account on bridgy, and there's no obvious way to choose between them.

we could fetch the home page and use the twitter rel-me link(s), or we could use twitter's search API, but both of those have the same problems: might find no twitter account, might find multiple.

we could say this is best effort, and choose the first one if available, otherwise use the home page link if there isn't any...but that behavior is unpredictable and surprising, so i'm reluctant.

i hate to say it, but i think https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb applies here. if you want the original post to link to a home page, and the POSSE tweet to @-mention, and you want to use bridgy publish, i'd probably encourage you to do the mapping yourself and use https://brid.gy/about#silo-content.

**Comment by snarfed** [comment]
(btw, you probably already know, but just in case, you can use the _Preview_ button on https://brid.gy/twitter/EddieHinkle to see what bridgy will do with a given post without actually tweeting.)

**Comment by snarfed** [comment]
related: https://indieweb.org/nicknames-cache

**Comment by EdwardHinkle** [comment]
Hmm, interesting. In my mind tel-me links make complete sense, and don't really feel like it makes overly smart. But self-mapping through silo-content makes sense for me and shouldn't be that difficult (as I do have a nicknames cache that connects people to other silos). I can implement this but it does feel like the conversion should be an expected user behavior :) In fact, I completely mis-read your comments earlier because I thought you were saying that it WAS implemented, as opposed to what you were saying which is mentally what it matches up with philosophically. :)

`</rant>`

I'll implement via silo-content.
