### ISSUE TITLE
broken twitter images

### ISSUE THREAD

**Issue by drikkes** [snarfed/bridgy#782]
I already asked this over at Known's github issues, and somebody suggested, it could be a bridgy problem.
https://github.com/idno/Known/issues/1969
Sometimes syndicated twitter likes don't get a profile image.
What can I do?

**Comment by snarfed** [comment]
hmm! happy to look into it. do you have an example URL?

**Comment by drikkes** [comment]
Yes, sure.
Here, Facebook worked, Twitter not. http://drikk.es/2017/erster
One Twitter profile broken, the other is fine. http://drikk.es/2017/alexa-kaufe-alles-von-seitenbacher
And I found one with a broken FB pic as well. http://drikk.es/2017/die-tvdirekt-hat-schnell-einen-clp-kommentar-geschaltet-zum-fall-thomas
Thanks for investigating!

**Comment by snarfed** [comment]
i checked a few of these, and they seem to be ok on bridgy's end. both broken twitter profile pictures on the http://drikk.es/2017/erster responses are ok:
* https://brid-gy.appspot.com/like/twitter/drikkes/933729772471050240/248732513
* https://brid-gy.appspot.com/like/twitter/drikkes/933729772471050240/18722530

and the facebook response on http://drikk.es/2017/die-tvdirekt-hat-schnell-einen-clp-kommentar-geschaltet-zum-fall-thomas is ok too:
* https://brid-gy.appspot.com/like/facebook/10206219375153745/10214333171593585/1717151104977519

the image URLs point to twitter and facebook themselves, not bridgy, and some of them (e.g. twitter's) do change when people change their profile pictures...but it looks like known fetches and stores them locally, so that's not the problem here.

let me know if i can help the known people debug!

**Comment by snarfed** [comment]
@drikkes looks like @mapkyca thinks upgrading your known version should help. let us know if it doesn't!

**Comment by drikkes** [comment]
Yes, thanks. Will see, if I find the time to update between christmas and new year's day. (I'm no admin pro, operations like this takes half a day or so for me...)
