### ISSUE TITLE
micropub API for bridgy publish

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#796]
when i started building bridgy publish [in early 2014](https://snarfed.org/2014-03-25_bridgy-publish), [micropub was just being born](https://indieweb.org/wiki/index.php?title=Micropub&dir=prev&action=history), so i [overloaded webmention](https://brid.gy/about#webmention) to be the trigger mechanism instead.

now that micropub is mature, we should support it too/instead. [some discussion on IRC.](https://chat.indieweb.org/dev/2018-02-26#t1519674081902000) @EdwardHinkle might be interested!

**Comment by snarfed** [comment]
for anyone looking into implementing this, you can basically take [`publish.py`](https://github.com/snarfed/bridgy/blob/master/publish.py) as a template, copy it to a new `micropub.py` file, drop all the interactive, HTTP fetching, and mf2 parsing code (`_find_source()` through `TwitterSendHandler`), and replace the mf2 parts in the rest with micropub handling.

auth is probably the one big open question. for a first pass, i'd recommend punting on it. just use the silo access token directly as the micropub. users could ask me for their token, or they can mint their own, per silo.

i'd also recommend punting on update, delete, media endpoint, and querying source content, at least to start.

**Comment by tantek** [comment]
The issue name “micropub for bridgy publish” sounded a lot like what I was looking for in <https://chat.indieweb.org/dev/2018-02-26/1519669277072200> but this issue is clearly about adding Micropub support as another API to Bridgy Publish, rather than adding another Bridgy Publish target to Micropub servers (for which I’ll file a separate issue).

Perhaps consider renaming this issue to something like:

Micropub API to Bridgy Publish

and I can file an issue for: Bridgy Publish to Micropub servers

Thanks!

(Originally published at: http://tantek.com/2018/057/t2/issue-name-micropub-bridgy-publish)

**Comment by snarfed** [comment]
sure! done.

**Comment by EdwardHinkle** [comment]
So, thinking through this a little bit while looking through the code. The Micropub post sent would become the post that gets syndicated. You still have to determine what service it gets syndicated through. I see a couple options here, currently the URLs used are:

POST /publish/preview
POST /publish/webmention
GET /publish/{service}

Micropub could either have a single endpoint:

POST /publish/micropub

And use a special mp- command to signify the silo or, what I think would be better is making

POST /publish/{service}
Or
POST /publish/micropub/{service}

An endpoint that fetches the service from the url, then no special data has to be passed through the object itself.

**Comment by aaronpk** [comment]
I would love to see this! I'm currently using [silo.pub](https://github.com/kylewm/silo.pub), which is a Micropub-to-silo gateway. It does a great job of exposing the Twitter API as a Micropub API. It also supports a few other silos but I only use it for Twitter. However, it hasn't had any updates since 2018, and the hosted service went down, so I'm running it on my server still and I would really like not to.

The Micropub API it provides is pretty complete, I don't think there would be much to change from how it currently works.

As far as the "which service to syndicate to" problem, you can solve that by using a different access token for each service. So there is only one micropub endpoint, `/publish/micropub`, and you would give a different access token out to each silo the user wants to publish to. That also provides an easy way to let the user publish to multiple different accounts at the same silo.

**Comment by dshanske** [comment]
Don't we have mp-destination now?

**Comment by snarfed** [comment]
Separate access tokens make sense! @aaronpk I wonder about the UX though. Any idea what fraction of Micropub clients let you manually enter a token? And if so, any idea how normal or awkward that would be to the average user?

It's probably the right MVP regardless. I just wonder, if we build and ship this and people like it, whether we'd eventually need to expand the UX to avoid manual token handling, eg implement the full IndieAuth flow so that people could enter brid.gy into their client, and presumably to a specific silo account with it, and they'd do the IndieAuth dance and brid.gy would give the client a token behind the scenes.

Or should we expect site servers like p3k to be the common case client, not end user clients/? Honestly I'm flailing a bit around the UX here. Maybe I'm overthinking it for now, and we just start with the manual token MVP and see how it goes.

**Comment by aaronpk** [comment]
I don't think end user Micropub clients are the use case here, because then you'd just be better off using the silo's own posting interface. The point of the API for me is to be able to automate posting to silos and not deal with their specific APIs.

You can definitely always start with the manual copy paste token approach, and then later add in the IndieAuth flow to it. silo.pub actually did implement the IndieAuth flow for it, it was a clever approach. Basically you'd enter a URL like `https://silopub.p3k.io/twitter.com/aaronpk` into your Micropub client, it would redirect to silopub, silopub would immediately redirect you to twitter, which would then redirect back through the chain. Basically from the user's point of view it looked just like a regular Twitter OAuth flow. But I don't think that's necessary for the first step.

**Comment by snarfed** [comment]
TODO(snarfed) before shipping: rewrite all `MastodonAuth` entities to get `access_token_str` indexed. snarfed/oauth-dropins@57305090c739c321a2395f121f2fb694f528487a

**Comment by snarfed** [comment]
Done ^

```py
with appengine_config.ndb_client.context():
  for m in MastodonAuth.query():
    print(m.key.id())
    m.put()
```

**Comment by snarfed** [comment]
This is live! Endpoint is https://brid.gy/micropub, supports create and delete and photo/video URLs but not update or file upload. Once you've enabled publish on your user page, there will be a _Get token_ button, use that as your Micropub token.
