### ISSUE TITLE
Bridgy Publish to GitHub: support tags to Labels

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#799]
It would be great if Bridgy could support publishing an issue with Labels to GitHub, and I think the right way to do this is via tags (e.g. class="p-category"). Note: apparently silo.pub does this.

Example issue: <http://tantek.com/2018/061/b1/css-cascade-3-test-suite-not-in-web-platform-tests> with tags for labels: css-cascade, css-cascade-3, Needs review of Test Case(s), PR blocker

And the POSSE copy on GitHub: <https://github.com/w3c/csswg-drafts/issues/2378> without any of the equivalent labels.

Note: it would be OK if Bridgy Publish to GitHub POSSEd tags only to *existing* labels in the target repo, and not create new tags. cc: [@aaronpk](https://github.com/aaronpk).

(Originally published at: http://tantek.com/2018/061/b2/bridgy-github-support-tags-labels)

**Comment by snarfed** [comment]
true!

i chose not to implement this originally because only repo owners can add labels to issues. eg for this issue, @tantek i don't see you in https://github.com/orgs/w3c/people?page=4 , so I'm guessing you're not an owner of csswg-drafts? which means bridgy couldn't add those labels for you anyway. i imagine that could be surprising sometimes, in general.

still maybe worth doing anyway though!

**Comment by snarfed** [comment]
shipped!
