### ISSUE TITLE
Support for Mastodon instances

### ISSUE THREAD

**Issue by ngm** [snarfed/bridgy#843]
Obviously [Bridgy Fed](https://github.com/snarfed/bridgy-fed) already exists for bridging to the Fediverse, and is great!  

However, I already have an account on a Mastodon instance, that I would quite like to keep at present.  It would be cool if Bridgy could POSSE to a Mastodon instance, and also retrieve the backfeed, in the same manner as it does with Twitter et al.

**Comment by snarfed** [comment]
yes! obligatory: [here are instructions for adding a new silo like mastodon.](https://bridgy.readthedocs.io/en/master/#adding-a-new-silo) PRs always welcome!

**Comment by drikkes** [comment]
Uh, that's too hard for an coding idiot like me...

**Comment by snarfed** [comment]
more discussion of syndicating to mastodon (vs federating) [today in #indieweb](https://chat.indieweb.org/2019-09-26#t1569516180881500) [and #-wordpress](https://chat.indieweb.org/wordpress/2019-09-26#t1569483741822500).

**Comment by snarfed** [comment]
[mastodon API docs.](https://docs.joinmastodon.org/api/) they do standard OAuth 2 and REST, independent of AP. wow ok.

also fascinating: as usual w/OAuth, they require registering apps beforehand...but since it's decentralized, there's no single place to register an app. so [they have an API for registering apps, per instance.](https://docs.joinmastodon.org/api/authentication/) makes sense, just a bit surprising.

**Comment by snarfed** [comment]
i threw together a very rough implementation of this. feel free to try it out: https://brid.gy/

**Comment by drikkes** [comment]
Works for me. Thanks!

**Comment by snarfed** [comment]
welcome!
