### ISSUE TITLE
message telling me to signup for bridgy has link back to my domain and not bridgy

### ISSUE THREAD

**Issue by jgmac1106** [snarfed/bridgy#847]
> Bridgy Error: Publish is not enabled for your account. Try signing up!

This is the error message I get. The target for the "try signing up!" link is my homepage. Not sure if this just the WordPress plugin and this is wrong repo.

**Comment by snarfed** [comment]
heh, funny. HTML bridgy error messages are really only designed to be rendered on https://brid.gy/ itself, so that link is actually local, just to `href="/"`, but it sounds like the wordpress plugin is rendering it unchanged inside your site.

hate to say it, but afaik @dshanske is planning to decommission that plugin anyway, so your long term fix is probably to migrate away from it.

**Comment by snarfed** [comment]
looks like this bit @asuh too: https://chat.indieweb.org/wordpress/2018-10-10#t1539200458651300
