### ISSUE TITLE
Bridgy on Instagram says my site doesn't support Webmention

### ISSUE THREAD

**Issue by Changelingmx** [snarfed/bridgy#868]
When I log into Bridgy via Instagram, it says I don't have webmention support. I'm already receiving webmentions from Twitter.

**Comment by snarfed** [comment]
hi again! the culprit here is that you have `u-url` on all of your h-card's `rel-me` links, including `https://www.instagram.com/changelingmx`. `u-url` means a link is the canonical URL for something, in this case _you_, since these are inside your h-card. so bridgy tries to believe you that `https://www.instagram.com/changelingmx` is your home page, looks for webmention support there, and doesn't find any.

i can update bridgy to ignore silo `u-urls`, but you'll still want to drop those `u-url` classes, especially since they'll probably similarly confuse other indieweb tools.

**Comment by Changelingmx** [comment]
I don't know what a u-url is. All I know is I filled out my profile in accordance with the directions for wordPress on indieweb.org. So far as I know, bridgy is the only thing giving me a problem, and it's specifically Instagram.

**Comment by dshanske** [comment]
Searching the wiki. This advice appears here. https://indieweb.org/discovery#Profile_Info

Here as well: https://indieweb.org/h-card#What_should_be_a_u-url_on_the_h-card_and_what_shouldn.E2.80.99t.3F

All WordPress sites using the Indieweb plugin, which this does, would follow the guidance listed on the wiki to that effect.

**Comment by dshanske** [comment]
My intepretation of u-url isn't that it is a canonical URL. As noted in the Microformats wiki, it indicates that special parsing required: prefer a/href, img/src, object/data etc. attributes to element contents. p- would indicate that the element contents were to be parsed as plaintext for the value. e- indicating the entire element and its hierarchy below it is the property...allowing for embedded markup.

**Comment by snarfed** [comment]
@dshanske huh. interesting. to be fair, https://indieweb.org/h-card#What_should_be_a_u-url_on_the_h-card_and_what_shouldn.E2.80.99t.3F asks exactly this question of whether `u-url` is just for home pages or for silo profiles too, and _doesn't_ answer it. it says mf1 implies the latter, mf2 implies the former, and gives examples of both in the wild.

i looked at a handful of indieweb sites, and they're pretty evenly split. we can query https://indiemap.org/ if we're really curious, but i'm going to handle it in bridgy anyway, so i'm not worried.

**Comment by snarfed** [comment]
@Changelingmx fixed! https://brid.gy/instagram/changelingmx looks good now. you can sign up again to get rid of the instagram.com/changelingmx profile link if you want, but you can also ignore it, it's harmless.

**Comment by Changelingmx** [comment]
Okay. It's working so I'm going to close this. Thank you. On a different but related note, is there a way to get the IndieWeb plugin to stop generating U-URLS?

**Comment by dshanske** [comment]
@Changelingmx No, only because there is a disagreement as to whether it is right or wrong to address. Will have to bring that to the community

**Comment by gRegorLove** [comment]
@dshanske @snarfed I updated https://indieweb.org/h-card#What_should_be_a_u-url_on_the_h-card_and_what_shouldn.E2.80.99t.3F based on Tantek's editorial update to the h-card spec.

I think the confusion might be because h-entry is a case where there is _usually_ only one `u-url` and it happens to be both the permalink and the canonical URL. Ideally, publishers should use `u-url u-uid` so it's explicitly the canonical URL.

h-cards are more likely to have multiple `u-url`, so it's not correct for consumers to assume a `u-url` is canonical without the `u-uid`.
