### ISSUE TITLE
Asterisk at the end of a tweet due to hidden syndicated links.

### ISSUE THREAD

**Issue by frankmeeuwsen** [snarfed/bridgy#876]
I use the Syndication Links plugin with my WordPress blog and use the Twitter via Bridgy option to POSSE my post to Twitter. In the Syndication Links settings, I disable the view of the syndication link and accompanying text. So the display is set on Hidden Links, I disabled all the ways to show the links and left the Text before Links option empty. But this does make a hidden list at the end of each post, to make sure there is a link to bridgy/publish/twitter. 
The tweet somehow gets an asterisk at the end of the text. You can see this in [the tweet](https://twitter.com/FrankLeTest/status/1142904717837774848) I use to test this. In the original text there is no asterisk. In the [Bridgy logfile](https://brid.gy/log?start_time=1561324693&key=aglzfmJyaWQtZ3lyTwsSDVB1Ymxpc2hlZFBhZ2UiKGh0dHBzOi8vZnJhbmttZWV1d3Nlbi54eXovMjAxOS8wNi8yMy82Mi8MCxIHUHVibGlzaBiAgMDmiMjZCAw) I can't quite see where this asterisk is added or why. Is this a bug, a specific behaviour I can fix myself or is something else?

**Comment by snarfed** [comment]
thanks for filing, frank, and sorry for the trouble!

the short answer is, bridgy doesn't try to understand or render CSS, so it doesn't know that your syndication links are hidden. it also translates HTML markup to Markdown-style text when publishing. so, it sees the list item at the end of your post, and converts it to a `*`-based list item, which shows up in your POSSEd tweet.

i get that Syndication Links is a convenient way to add the `brid.gy/publish/twitter` link, but it's probably not the best idea, since it causes this problem. hey @dshanske, if this isn't really the right way to use Bridgy Publish with WordPress these days, what do you recommend instead?

**Comment by dshanske** [comment]
@snarfed Syndication Links has built in support for this. So it is my recommended tool

**Comment by dshanske** [comment]
I did not account for this scenario.

**Comment by snarfed** [comment]
np! i'll tentatively close this then. let me know if you want me to file a Syndication Links issue.

**Comment by frankmeeuwsen** [comment]
I’ll file an issue. Since this might be a new  scenario it’s worth considering how to deal with it.
