### ISSUE TITLE
401 Unauthorized error on twitter page

### ISSUE THREAD

**Issue by ats** [snarfed/bridgy#879]
I'm receiving a 401 Unauthorized error trying to access my page at https://brid.gy/twitter/schussman. I've tried the steps described [here](https://github.com/snarfed/bridgy/issues/263) and in the FAQ, but I think this situation is slightly different in that I can't access my brid.gy user page at all. I've revoked access at Twitter and re-authorized but it hasn't changed. Any ideas?

**Comment by snarfed** [comment]
hey, yes! sorry for the trouble. i blocked it because you (or someone else?) subscribed to your bridgy page in an indie reader at some point, which fetches it once every minute or so, which is not really a use case (or load) i plan to support.

mind unsubscribing in your reader? i've unblocked your user page for now. apologies again for the trouble.

**Comment by ats** [comment]
Yikes! Sorry about that. I think I was experimenting with Aperture, maybe wondering if it would aggregate those pings there. I've removed it, so should be all resolved, now.

Thanks for the quick look at this! Sorry for the hassle.
