### ISSUE TITLE
Brid.gy parsing root domain not subdirectory

### ISSUE THREAD

**Issue by jasonrbriggs** [snarfed/bridgy#881]
Absolutely not sure if this is a bug or something stupid I've done (I suspect the latter).  I only see one "toot" when I subscribe to myself (@jasonrbriggs.com@jasonrbriggs.com) from a mastodon account.  If I check the brid.gy logs I see this:

```
2019-08-18 13:51:14.749227 I refetching h-feed for source jasonrbriggs (GitHub)
2019-08-18 13:51:14.749402 D attempting to refetch h-feed for jasonrbriggs (GitHub)
2019-08-18 13:51:14.752676 I requests.head http://jasonrbriggs.com/ {'headers': {'User-Agent': u'...'}}
2019-08-18 13:51:15.168866 D Resolved http://jasonrbriggs.com/ to http://jasonrbriggs.com/journal/
2019-08-18 13:51:15.207884 D fetching author url http://jasonrbriggs.com/journal/
```
I recently updated my github profile to point to "http://jasonrbriggs.com/micro", so the fact that brid.gy goes from jasonrbriggs.com and is then being redirected by my site to /journal seems wrong.  That would explain why I'm not seeing my latest micro blog posts (which are posted from the subdir "/micro") but doesn't explain why I see a post at all.  

Not sure what I've done wrong here...  any clues?

**Comment by snarfed** [comment]
hi Jason! sounds like you're trying to federate posts from your site to Mastodon? and not send replies from Github back to your site? https://fed.brid.gy/ is for the former, https://brid.gy/ is for the latter. they share the "Bridgy" name/branding, but otherwise they're entirely separate services. so your GitHub profile and logs on your https://brid.gy/ user page are both unrelated to https://fed.brid.gy/ federating posts from your site to Mastodon.

apologies for the confusion!

**Comment by jasonrbriggs** [comment]
@snarfed Thanks for the reply.  I've signed up for both brid.gy and fed.brid.gy and I originally thought that fed.brid.gy was supposed to be the service federating the posts -- then it didn't seem to work properly and I went back to brid.gy thinking I might've misunderstood how this is supposed to work.  I'll close this issue and perhaps raise against https://github.com/snarfed/bridgy-fed/ if I still can't figure this out...?
