### ISSUE TITLE
Twitter replies now contain nicks in content

### ISSUE THREAD

**Issue by sonniesedge** [snarfed/bridgy#882]
<https://brid-gy.appspot.com/comment/twitter/sonniesedge/1163476995524743168/1163484323376500741>

I'm pretty sure Twitter replies did not always contain the nicks of those in a conversation. Has this always been the case? They're suddenly showing up all over my blog comments. https://www.sonniesedge.net/bookmarks/3123/#replies

**Comment by sonniesedge** [comment]
Yeah, just checked. Older ones don't show the nicks in the content. 

https://brid-gy.appspot.com/comment/twitter/sonniesedge/1161374434667696128/1161568211424468993
https://www.sonniesedge.net/notes/3075/

**Comment by armingrewe** [comment]
I noticed that as well, started may be on Friday 16/Aug (earliest occurrence I can find), but could have been earlier. Was fine on Sat 10/Aug (I didn't have any replies between 10/Aug and 16/Aug). Didn't have the time to look at it.

Example from my blog: http://www.islay.org.uk/2019/08/19/machir-bay-coastal-scene-at-low-tide-isle-of-islay/#comments

**Comment by snarfed** [comment]
ugh, yes. apologies for the regression, all! absolutely true. we discussed this in indieweb chat recently, https://chat.indieweb.org/dev/2019-08-17#t1566051874494100 . cc @aaronpk.

the bug was introduced in https://github.com/snarfed/granary/commit/cec7759ddf1049182543e4a7b09d78b59cdd079f , so referring that commit would fix it. sadly I'm on vacation without a computer until 8/26, and other than me, only @kylewm has deploy access, so we're probably stuck with it until then.

sorry for the bad news. I'll help you all fix and resend all affected webmentions as soon as I'm back!

**Comment by sonniesedge** [comment]
Ah, thanks for figuring that out. It's something I can certainly live with until a deploy!

Thank you for making brid.gy and offering it for free!

**Comment by armingrewe** [comment]
Same here, I can wait. I don't get that many replies (as far as I can tell it's only a problem with replies, other types seem ok), it's not a major issue.

Enjoy your holidays!

**Comment by snarfed** [comment]
fixed! confirmed on https://aaronparecki.com/2019/08/25/4/ by re-sending the reply from LimeAID; it had trailing usernames before.

i'll look into re-sending all affected wms. in the meantime, feel free to retry any manually from your user pages.

**Comment by sonniesedge** [comment]
Thanks for fixing this @snarfed! Can confirm fixed also.
