### ISSUE TITLE
Allow to trigger 'Resend for post'

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy#888]
This is totally a feature request, and I'd understand if you wouldn't do this.

I had some problems (well, depends on how you look at it of course). Some syndication links weren't found, and the polling for my site was limited to 24 hours, so it missed some 'fast' reactions on twitter etc. Probably because I haven't been that active for a while, which is fine.

Now, pushing the 'Recrawl' site button didn't help immediately, it still didn't find a specific twitter syndication link for a post. Entering the url in the 'Resend for post' textfield did the trick, and likes en comments came back as webmentions since there's now a webmention target.

I was wondering whether I'd be possible to allow this feature to be called with some sort of API call. e.g. I would ping bridgy on brid.g./account/discover?url=https://example.com/post. I imagine the controller would of course need some some sort of authentication (maybe every account gets a token which is available on the bridgy user page), then does some throttling so we don't spam you every second, then checks whether there's a known syndication, and if not, do what the textfield feature on the site does.

Hope this makes sense. And totally fine if this not in scope at all :)

**Comment by swentel** [comment]
I wonder, maybe one way to 'fix' this, is to store the syndication url already locally in bridgy.

What I mean is this: I used bridgy to publish to twitter, and for instance 'https://realize.be/comment/indieweb/4543' was posted. Bridgy didn't have a syndication link yet, so a response to that one on twitter was not send to this target. I had to enter it again in the 'Resend for post' and then refresh. (after I also fixed the webmention support, but that was my problem)

So I  was just wondering whether it wouldn't make sense for brid.gy to store post url already with the syndication url it gets from twitter because, well, you have that information as I get it back when it's published so I can render it on the post so that brid.gy would it discover it later - seems like a unnecessary loop - unless you already to this, then I will shut up :)

**Comment by snarfed** [comment]
hey, thanks for the detailed thoughts and suggestions!

resend API and storing published synd links are both reasonable. i'm inclined to focus on the specific syndication URL that crawling missed, though, since that's definitely a bug, and fixing that will help all bridgy users, not just the minority who might adopt a resend API or use publish.

which post and tweet was it? i'm happy to wade through the logs on my end and try to debug the crawl more.

**Comment by swentel** [comment]
Makes sense, this was the post: https://realize.be/image/100 
No rush!

**Comment by snarfed** [comment]
ok! i had a chance to dig into this. looks like https://realize.be/ was redirecting to http://translatoruser-int.com/ during this period, which returned HTTP 400, which is why crawling didn't find your new syndication link. it couldn't fetch your site at all.

[here's an example log of the redirect.](https://brid.gy/log?start_time=1569399628&key=aglzfmJyaWQtZ3lyFAsSB1R3aXR0ZXIiB3N3ZW50ZW) relevant snippet:
```
2019-09-25 08:28:52.608078 I requests.get https://realize.be/ {'headers': {'User-Agent': u'...'}}
2019-09-25 08:28:53.075560 I Could not fetch author url https://realize.be/
Traceback (most recent call last):
  File ".../original_post_discovery.py", line 276, in _process_author
    author_resp.raise_for_status()
  File ".../local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: None for url: http://translatoruser-int.com/
```

bridgy has been able to crawl your site ok since then - [example log](https://brid.gy/log?start_time=1569511028&key=aglzfmJyaWQtZ3lyFAsSB1R3aXR0ZXIiB3N3ZW50ZWwM) - so it must have been transient.

here are all of the poll now/crawl now attempts i saw in logs. the twitter API 401s are probably because you logged into bridgy with twitter again during them, which invalidated the existing access token.

* 2019-09-25 01:19:47.175 PDT  twitter API 401ed, disabled
* 2019-09-25 01:20:25.007 PDT  twitter API 401ed, disabled
* 2019-09-25 01:20:28.264 PDT  crawled https://realize.be/ , redirect to http://translatoruser-int.com/, 400ed
* 2019-09-25 01:21:00.986 PDT  twitter API 401ed, disabled
* 2019-09-25 01:22:57.481 PDT  poll succeeded, skipped crawl
* 2019-09-25 01:24:20.369 PDT  poll succeeded, skipped crawl
* 2019-09-25 01:28:49.449 PDT  crawled https://realize.be/ , redirect to http://translatoruser-int.com/, 400ed
* 2019-09-25 02:02:47.860 PDT  poll succeeded, skipped crawl
* 2019-09-25 02:02:52.312 PDT  poll succeeded, skipped crawl

**Comment by swentel** [comment]
I stumbled on that that yesterday as well. It looks there was some cache poisoning tricking varnish to redirect, and only for my homepage, which is weird -  still haven't found out what happened there.

So yes, 

- this might haven been the problem all along, thanks for checking the logs, sorry for the noise here :/
- some new likes and a comment came in, so I think everything is back to normal

I do remember though seeing a crawl log saying something about 'found 10 items, skipping the rest' (or something alike, I can't remember exactly), so I was wondering: I have two rel="feed' link tags, and bridgy scans both, but in a way, only the 'timeline/all' is the most important one for bridgy to get all syndication links (especially on comments). Can I tell somehow to ignore the other one?

**Comment by snarfed** [comment]
yes! bridgy crawls for new syndication links every 6h by default, and falls back to every 2d if it hasn't seen a new synd link in the last 2w. it looks in entries in h-feeds themselves, and if they don't have synd links, it also fetches individual h-entry permalinks and looks there. it stops at 10 h-entry permalinks per crawl.

it's generally only looking for _new_ synd links in each crawl, so this is generally fine unless you have very high feed velocity, ie you have more than 10 posts every 6h, or every 2d if you don't publish synd links inside your h-feed. details in #771. let me know if you think that might apply to your site! otherwise you probably don't need to worry.

**Comment by swentel** [comment]
I guess I had a high velocity at that moment, especially adding comments myself quite a bit.
I don't think it really applies to my site since I haven't had problems in the past.

So closing for now, thanks for the feedback!

**Comment by snarfed** [comment]
oh, the "skipping" message didn't mean it actually _missed_ any entries or synd links. it just means that's where it stopped during that crawl. i expect it still found any new synd links. (log messages are meant primarily for me; they're not designed to be too user friendly or understandable. 😁)

regardless, glad we figured this out!
