### ISSUE TITLE
Blocking specific twitter users

### ISSUE THREAD

**Issue by evert** [snarfed/bridgy#889]
Hi there! I'm a happy user of bridgy and I've been using it for over a year.

There 4 users on twitter that seem to subscribe to my RSS feed and tweet anything that comes up. I don't mind that they do, but it causes every blogpost to show the same 4 uninteresting webmentions.

I would like to be able to just filter them out. Is there a way to do this today?

**Comment by snarfed** [comment]
hmm, interesting!

i can think of a couple ways. first, bridgy obeys your twitter block list, so if you block them, bridgy will stop send you webmentions from them. https://brid.gy/about#block+list

otherwise, we tend to think that the best place for moderation is in your own web site, more than in services like bridgy. some background: https://indieweb.org/moderation . i don't know how jekyll's webmention plugin (?) works, but might be worth a feature request there?

we're discussing this a bit in indieweb chat right now btw, feel free to join us!

**Comment by snarfed** [comment]
oops, hit the wrong button, didn't mean to close yet.

**Comment by evert** [comment]
I was thinking of using Twitter's block list, but I felt that that was a bit too aggressive and might send the wrong message to these accounts (I don't hate them or anything).

I actually wrote my own webmention script that uses webmention.io. Webmention.io itself does offer a way to block per domain, but I would just end up blocking all of brid.gy 

Gonna look for that indieweb chat!

**Comment by snarfed** [comment]
glad your own script is working! tentatively closing, since we have two existing options for this, twitter block lists and your own site. feel free to reopen if necessary.
