### ISSUE TITLE
Not including the text of tweets in webmentions

### ISSUE THREAD

**Issue by pamoroso** [snarfed/bridgy#890]
I connected my Blogger blog and Twitter account to Bridgy, and webmentions work great. Thanks!

However, I feel a bit nervous about copying in my blog's comments the full text of other users' tweets, especially considering most of them may not be aware of it.

Is it possible to configure Bridgy to replace the full text with generic text linking to the relevant tweets, such as *Alice mentioned this in [a tweet](https://www.example.com)* or *Alice replied to this in [a tweet](https://www.example.com)*? And maybe aggregate similar reactions like *[Alice](https://www.example.com) and [Bob](https://www.example.com) mentioned this on Twitter*.

If it's not possible it would be a useful feature.

**Comment by snarfed** [comment]
hi paulo! great point; this is a very valid concern. we've discussed it ourselves before too: https://indieweb.org/backfeed#Discussion

we've generally concluded that your web site itself is the best place to moderate incoming webmentions, customize how they're displayed, etc. this case is a bit different though, since blogger isn't directly aware of webmentions itself. even so, does blogger itself offer an option to hide comment text like you want?

if not, this is a reasonable feature request. you're welcome to dive in and implement it yourself! bridgy development docs are at https://bridgy.readthedocs.io/ ; i'm happy to help with any questions!

also, in case it helps, bridgy only sends fully public tweets (etc) to your site. your concern is still valid, but just fwiw. https://brid.gy/about#public

**Comment by pamoroso** [comment]
Thanks for the information @snarfed, you make some good points too. Blogger does support removing comments but, given the typical volume of Twitter reactions, doing this manually is impractical and doesn't scale.

I have unfortunately not enough experience with Python or Google Cloud, so I'm unable to contribute. Therefore, for the time being I've turned off listening to Twitter webmentions from Twitter.

**Comment by snarfed** [comment]
understood! sorry we don't have a better answer yet.

tentatively closing. feel free to reopen if anything changes.
