### ISSUE TITLE
Fix unit test command in docs

### ISSUE THREAD

**Issue by fancypantalons** [snarfed/bridgy#926]
The offending test is located in `oauth_dropins/webutil/tests/test_util.py`, in the method `test_tag_uri`.  Here's the body for the test method:

```python3
    self.assertequal('tag:x.com:foo', util.tag_uri('x.com', 'foo'))
    self.assertequal('tag:x.com,2013:foo',
                      util.tag_uri('x.com', 'foo', year=2013))
```

So, let's look at the tag_uri method in the util module:

```python3
def tag_uri(domain, name, year=None):
  """Returns a tag URI string for the given domain and name.

  Example return value: 'tag:twitter.com,2012:snarfed_org/172417043893731329'

  Background on tag URIs: http://taguri.org/
  """
  if year is not None:
    year = ',%s' % year
  else:
    year = ''
  return 'tag:%s%s:%s' % (domain, year, name)
```

Huh... that... looks right.  I cannot tell you how utterly confused I was by this.  Desperate, I added some code to dump a callstack from this method when that test was calling it, and that lead me to this little nugget in `appengine_config.py`:

```
from oauth_dropins.webutil import util
util._orig_tag_uri = util.tag_uri
util.tag_uri = lambda domain, name: util._orig_tag_uri(domain, name, year=2013)
```

Doh!  The method gets hot replaced with a wrapper lambda that a) hard codes the year to 2013, and b) doesn't take a year argument as an optional parameter.  So the first assertion in the test fails because of the hard coded year, and the second test would fail (if the assertion was hit) because the optional argument isn't present.

---

The fix is pretty obvious, though I'm not thrilled by it, since it's pretty hacky and non-obvious:

```python3
    self.assertequal('tag:x.com,2013:foo', util.tag_uri('x.com', 'foo'))
```

I'm open to other suggestions... I could, for example, unwrap the wrapper in the test class setUp method, although that's ugly in its own way...

**Comment by snarfed** [comment]
wow. thank you for the details, and apologies for the wild goose chase! that monkey patch is indeed a historical wart in the codebase. necessary, but obviously not pretty or ideal.

are you using `python setup.py test` to run the tests? if so, that's probably the problem. i haven't consistently maintained that entry point. mind trying this instead? it's what i use.

```sh
source local3/bin/activate
gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 < /dev/null >& /dev/null &
python3 -m unittest discover
kill %1
```

(the datastore emulator is only needed for `StringIdModelTest.test_put`. feel free to skip it if you want and confirm that only that test fails.)

if that works, then fortunately, the problem is just that `setup.py test` isn't currently supported. so, we should fix it, and also update the docs to use the commands above instead, at least the datastore emulator part.

apologies again for the confusion!

**Comment by snarfed** [comment]
oh wait, sorry, didn't realize this issue is in the bridgy project. i think this is just another instance of docs needing an update. specifically, granary and oauth-dropins have their own projects and pypi packages and tests, so i don't really intend for their tests to be runnable inside bridgy. i think the fix is to update the `python3 -m unittest discover` in the docs to `python3 -m unittest discover` to run just bridgy's tests.

**Comment by snarfed** [comment]
(as background, the codebases and dev toolchains for these projects changed substantially recently when i migrated them from python 2 to 3, and more significantly from app engine's python 2 runtime to its python 3 runtime. i tried to update all the docs etc that needed it, but i clearly didn't catch everything. you may be the first person to go through the new instructions from scratch since that migration. apologioes, and thank you for finding the doc bugs!)

**Comment by fancypantalons** [comment]
My pleasure!  I'll throw together a quick PR to fix up UT invocation instructions in the next day or two once I find a couple free cycles.
