### ISSUE TITLE
[reddit] "Add web site" page has a Content Security Policy error, and does not show the image

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#938]
Noticed when I signed up using `FireFox Nightly 76.0a1 (2020-04-06) (64-bit)`:

![2020-05-02-112800_925x840_scrot](https://user-images.githubusercontent.com/3315059/80861698-18df5b80-8c68-11ea-8d33-8c738f7e6e43.png)

However, I'm not sure whether the image not being present is the same root cause as this CSP error.

**Comment by snarfed** [comment]
hmm! i don't actually see that problem on firefox 75.0:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/778068/80866210-58934c80-8c42-11ea-9a53-3f25bf3f9ff0.png">

**Comment by snarfed** [comment]
@jamietanna friendly ping?

**Comment by jamietanna** [comment]
I'm still seeing it, on ff77 (which I've just been upgraded to), but can't see it on ff75. I wonder if it's something new they're adding?

**Comment by jamietanna** [comment]
Or could it be something wrong with my user, perhaps?

**Comment by snarfed** [comment]
hmm! ok. another step could be to try to repro it in firefox's safe mode, which i think would disable any browser settings, custom plugins, etc that might be affecting this. i'd hope we'd see a different console error message in that case, though, so only a guess...but it's complaining about a script inside a `data:`, which bridgy doesn't use at all, so i do kind of suspect a greasemonkey script or plugin or something similar.

otherwise, i still haven't reproed this, so if you do find time to dig in, please feel free!

**Comment by snarfed** [comment]
@jamietanna checking in on this again, do you still see it on both of your reddit accounts? i'd love to fix this, but i still haven't managed to repro it myself.

**Comment by jamietanna** [comment]
I've managed to track it down to being the [DuckDuckGo Privacy Essentials](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/) FIrefox extension. With that disabled, I can see the images again. So we can close this 👍

(Originally published at: https://www.jvt.me/mf2/2020/07/or4xo/)

**Comment by snarfed** [comment]
aha. thanks for the extra sleuthing!
