### ISSUE TITLE
Webmention posting to Twitter fails with 'Couldn't find link to www.brid.gy/publish/twitter'

### ISSUE THREAD

**Issue by lildude** [snarfed/bridgy#989]
I'm experimenting with using Bridgy and I'm hitting a problem when attempting to POST a webmention as detailed in the documentation or using the curl command provided by the preview fails:

```console
$ curl -d 'source=https://lildude.github.io/dev-micropub-pages/and-now-weve-got-the&target=https://brid.gy/publish/twitter' https://brid.gy/publish/webmention
{
  "error": "Couldn't find link to www.brid.gy/publish/twitter"
}
```

Posting using the web interface works.

I suspect something might be up with the server side of things.

## Meta:

Account: https://brid.gy/twitter/fundiworks
Log entry: [here](https://brid.gy/log?start_time=1605807655&key=agdicmlkLWd5cmgLEg1QdWJsaXNoZWRQYWdlIkFodHRwczovL2xpbGR1ZGUuZ2l0aHViLmlvL2Rldi1taWNyb3B1Yi1wYWdlcy9hbmQtbm93LXdldmUtZ290LXRoZQwLEgdQdWJsaXNoGICA8Lq48JoKDA) though I can't get it to load.

**Comment by snarfed** [comment]
sorry for the trouble! the error message here is right: to publish via webmention, you need a link to brid.gy/publish/twitter somewhere in your post to confirm your intent to publish it. details: https://brid.gy/about#webmentions . interactive via the web site doesn't need that because it logs you into your twitter account to verify your identity.

**Comment by lildude** [comment]
🤦 Of course. I completely missed that and misunderstood the message too. Adding in the link does the trick. Thanks.
